/**
 * The grant scan for this module's tests, generated by system1 `adopt`, and
 * the scan `pnpm validate` runs over adopt's templates (0020).
 *
 * `adopt` only ever writes the marked line set to "off"; turning it on is the
 * user's edit. This is an allowlist for the name, read one line at a time:
 * - the marked line is a `const` (TS) or `Final` (Python) set to "off";
 * - every other use of the name in code is a comparison, an import, an
 *   assertion, a read, or the runtime's option given exactly the name, as the
 *   last property of the runtime call's object literal, which also names
 *   this file (`module: import.meta.url`, so the runtime reads the marked
 *   line too), in the file that declares it;
 * - a Unicode line separator, or a backslash-u escape in TS code, is refused.
 *
 * Comments and string contents are skipped. It reads text, not what runs: a
 * computed key, or code elsewhere that calls the runtime, can still pass it,
 * so the user's review of the diff is the control. The words are assembled so
 * this file carries no grant of its own.
 */
const [E, e] = ["EG" + "RESS", "egr" + "ess"]
const MARKER = ["system1", ": runtime ", e].join("")
const CREATE = "createPolicy" + "Runtime"

// U+2028 and U+2029, built so no backslash-u escape appears in this code.
const SEPARATORS = String.fromCharCode(0x2028, 0x2029)
const SEPARATOR = new RegExp(`[${SEPARATORS}]`)
const LINE_END = new RegExp(`\\r\\n|[\\r\\n${SEPARATORS}]`)
const OFF_LINE = new RegExp(
  `^(?:(?:export\\s+)?const\\s+${E}\\s*(?::\\s*[\\w.[\\]|,"' ]+?\\s*)?=\\s*(["'])off\\1\\s*(?:(?:as|satisfies)\\s+[\\w.]+\\s*)?;?\\s*\\/\\/|${E}\\s*:\\s*(?:typing\\.)?Final(?:\\[[\\w.[\\]|,"' ]+\\])?\\s*=\\s*(["'])off\\2\\s*#)\\s*${MARKER}`,
)
const NAME = new RegExp(`\\b${E}\\b`, "g")
const WORD = new RegExp(`\\b${e}\\b(?!-)`, "g")
const ONE_LINE_IMPORT =
  /^\s*(?:import\s*(?:type\s*)?\{[^}]*\}\s*from\s|from\s+[\w.]+\s+import\s+[\w\s,]*$)/
const GIVEN_BEFORE = new RegExp(`\\b${e}\\s*:\\s*$`)
const GIVEN = new RegExp(`^\\s*:\\s*${E}\\s*,?\\s*(\\}\\s*\\))?`)
const QUOTED = new RegExp(`["'\`]${e}["'\`]`)
const BY_NAME = new RegExp(`\\.${e}\\b|\\b${e}\\s*\\(`)
const CONSENT = new RegExp(`${e}Consent`, "i")
const ENV = /process\.env|os\.environ|getenv/
const REFLECTION = /\bsetattr\s*\(|\bglobals\s*\(|\b__dict__\b|Object\.defineProperty|Reflect\.set/
const GRANT_STARTS = new RegExp(`^\\s*${e}\\s*:`)
const MODULE_THEN_GRANT = new RegExp(`^\\s*import\\.meta\\.url\\s*(?:,\\s*(?:${e}\\s*:.*)?)?$`)
const CALLS = new RegExp(`\\b${CREATE}\\s*\\(`)
const OPENS = new RegExp(`\\b${CREATE}\\s*\\(\\s*\\{`)
/** Strings, left to right. A template literal keeps only its `${…}` code. */
const STRINGS = new RegExp(
  [
    "`(?:[^`\\\\]|\\\\.)*`",
    `(?<![fF])(?<![fF][rRbB])"(?:[^"\\\\]|\\\\.)*"`,
    `(?<![fF])(?<![fF][rRbB])'(?:[^'\\\\]|\\\\.)*'`,
  ].join("|"),
  "g",
)

/** Everything in `source` that could grant runtime egress; `python` for a `.py` file. */
export function grantProblems(source: string, python = false): string[] {
  const problems: string[] = []
  if (SEPARATOR.test(source)) problems.push("a Unicode line separator (U+2028/U+2029)")
  const lines = source.split(LINE_END)
  const marked = lines.filter((line) => line.includes(MARKER))
  if (marked.length > 1) problems.push(`${marked.length} lines carry the marker, not one`)
  const declares = marked.length === 1 && OFF_LINE.test(marked[0] as string)
  const codes = codeLines(lines, python)
  const nextCode = (i: number) => codes.slice(i + 1).find((c) => c.trim() !== "") ?? ""
  // Parentheses still open in the runtime call, from its `(`; 0 outside it.
  let depth = 0
  // Whether the open runtime call has named this file (module: import.meta.url).
  let callModule = false
  // Open braces of the runtime call's options object, and whether it has closed.
  let braces = 0
  let objClosed = false
  const parens = (text: string) =>
    (text.match(/\(/g)?.length ?? 0) - (text.match(/\)/g)?.length ?? 0)
  for (const [i, line] of lines.entries()) {
    const at = `line ${i + 1}`
    if (line.includes(MARKER)) {
      if (!OFF_LINE.test(line))
        problems.push(`${at}: the marked line isn't a constant set to "off"`)
      continue
    }
    const code = codes[i] as string
    if (code.trim() === "") continue
    if (!python && code.includes("\\u")) problems.push(`${at}: a backslash-u escape in code`)
    if (python && line.includes('"--module"') && !/abspath\(__file__\)/.test(code + nextCode(i)))
      problems.push(`${at}: --module isn't this file (os.path.abspath(__file__))`)
    if (CALLS.test(code) && !OPENS.test(code))
      problems.push(`${at}: ${CREATE} not given an object literal`)
    const start = depth > 0 ? 0 : (OPENS.exec(code)?.index ?? -1)
    const inCall = start >= 0
    const left = inCall ? depth + parens(code.slice(start)) : 0
    // Braces of the call's options object, before each character: `module` and
    // the grant must sit at its top level, and its closing `}` must close the
    // call, so no other object (a second argument, `|| {…}`) can stand in.
    const opened = depth > 0 ? undefined : OPENS.exec(code)
    const objStart = opened ? opened.index + opened[0].length - 1 : 0
    const level: number[] = []
    let b = inCall ? braces : 0
    for (let k = 0; k < code.length; k++) {
      level[k] = b
      if (!inCall || k < objStart || objClosed) continue
      if (code[k] === "{") b++
      else if (code[k] === "}" && --b === 0) {
        objClosed = true
        const tail = code.slice(k + 1)
        if (!/^\s*\)/.test(tail) && !(tail.trim() === "" && /^\s*\)/.test(nextCode(i))))
          problems.push(`${at}: the runtime's options object ends before its call does`)
      }
    }
    // `module: import.meta.url` must sit right before the grant: anything between
    // (a spread, say) could replace it.
    if (inCall && (depth === 0 || !GRANT_STARTS.test(code))) callModule = false
    for (const m of code.matchAll(/\bmodule\s*:(?!:)/g)) {
      if (!inCall) continue
      if (level[m.index ?? 0] !== 1) {
        problems.push(`${at}: the runtime's module not at the top of its options object`)
        continue
      }
      const rest = code.slice((m.index ?? 0) + m[0].length)
      if (!/^\s*import\.meta\.url\b/.test(rest))
        problems.push(`${at}: the runtime's module given anything but import.meta.url`)
      else callModule = MODULE_THEN_GRANT.test(rest)
    }
    for (const m of code.matchAll(NAME)) {
      const before = code.slice(0, m.index)
      const after = code.slice((m.index ?? 0) + m[0].length)
      const allowed =
        /^\s*[!=]==?(?!=)/.test(after) ||
        /[!=]==?\s*$/.test(before) ||
        ONE_LINE_IMPORT.test(code) ||
        (/\(\s*$/.test(before) && /^\s*(?:\)|,\s*""\s*[,)])/.test(after)) ||
        (/\w\.$/.test(before) && !/^\s*[-+*/|&]?=(?!=)/.test(after)) ||
        inImportList(lines, i) ||
        GIVEN_BEFORE.test(before)
      if (!allowed) problems.push(`${at}: ${E} used other than as allowed`)
    }
    for (const m of code.matchAll(WORD)) {
      const rest = code.slice((m.index ?? 0) + m[0].length)
      if (/^\s*[:=](?!=)/.test(rest)) {
        const given = GIVEN.exec(rest)
        const tail = given ? rest.slice(given[0].length) : rest
        // Last in the call's object: the call closes right after it.
        const closes =
          (given?.[1] !== undefined && left === 0) ||
          (tail.trim() === "" && left === 1 && /^\s*\}\s*\)/.test(nextCode(i)))
        if (!given || !closes || !inCall || level[m.index ?? 0] !== 1)
          problems.push(`${at}: the runtime given anything but ${E}, last in ${CREATE}({…})`)
        else if (!callModule)
          problems.push(
            `${at}: the runtime call doesn't name this file right before the grant (module: import.meta.url)`,
          )
        else if (!declares)
          problems.push(`${at}: the runtime given a ${E} this file doesn't declare`)
      } else if (/^\s*[,})]/.test(rest)) problems.push(`${at}: the grant passed as a variable`)
    }
    if (BY_NAME.test(code) || QUOTED.test(line)) problems.push(`${at}: the grant set by name`)
    if (CONSENT.test(line)) problems.push(`${at}: a consent option`)
    if (REFLECTION.test(code)) problems.push(`${at}: a binding set by reflection`)
    if (new RegExp(`\\b${E}\\b`).test(line) && ENV.test(line))
      problems.push(`${at}: ${E} read from the environment`)
    depth = Math.max(left, 0)
    braces = depth > 0 ? b : 0
    if (depth === 0) objClosed = false
  }
  return problems
}

/**
 * Each line as code only: comments removed (block comments tracked across
 * lines in TS, docstrings in Python) and string contents blanked.
 */
function codeLines(lines: string[], python: boolean): string[] {
  let inBlock = false
  let inDoc: string | undefined
  return lines.map((raw) => {
    let line = raw
    if (python) {
      if (inDoc) {
        const end = line.indexOf(inDoc)
        if (end < 0) return ""
        line = line.slice(end + 3)
        inDoc = undefined
      }
      line = line.replace(/("""|''')[\s\S]*?\1/g, '""')
      const open = /"""|'''/.exec(line)
      if (open) {
        inDoc = open[0]
        line = line.slice(0, open.index)
      }
      return line.replace(STRINGS, '""').replaceAll(`\`${E}\``, "").replace(/#.*$/, "")
    }
    if (inBlock) {
      const end = line.indexOf("*/")
      if (end < 0) return ""
      line = line.slice(end + 2)
      inBlock = false
    }
    line = line.replace(STRINGS, (s) =>
      s.startsWith("`")
        ? ` ${[...s.matchAll(/\$\{([^}]*)\}/g)].map((m) => m[1]).join(" ")} `
        : '""',
    )
    line = line.replace(/\/\*[\s\S]*?\*\//g, " ")
    const open = line.indexOf("/*")
    if (open >= 0) {
      inBlock = true
      line = line.slice(0, open)
    }
    return line.replace(/\/\/.*$/, "")
  })
}

/** Is line `i` a bare item of a multi-line import (TS `import {…} from`, Python `from … import (…)`)? */
function inImportList(lines: string[], i: number): boolean {
  const strip = (l: string) => l.replace(/\s*(?:\/\/|#).*$/, "")
  if (!new RegExp(`^\\s*${E}\\s*,?\\s*$`).test(strip(lines[i] as string))) return false
  const item = /^\s*(?:type\s+)?\w+(?:\s+as\s+\w+)?\s*,?\s*$/
  let start = i - 1
  while (start >= 0 && item.test(strip(lines[start] as string))) start--
  let end = i + 1
  while (end < lines.length && item.test(strip(lines[end] as string))) end++
  const open = strip(lines[start] ?? "")
  const close = strip(lines[end] ?? "")
  return (
    (/^\s*import\s*(?:type\s*)?(?:\w+\s*,\s*)?\{\s*$/.test(open) &&
      /^\s*\}\s*from\s/.test(close)) ||
    (/^\s*from\s+[\w.]+\s+import\s*\(\s*$/.test(open) && /^\s*\)\s*$/.test(close))
  )
}
