/**
 * The regex router's result in the `route-hint` answer space, generated by
 * system1 `adopt`. The shadow harness writes it as each captured row's
 * `current`, so `decide compare` can set the regex's answers beside the
 * decision model's, question by question.
 *
 * Strict, like `compare`'s own reading: a trigger the question set doesn't
 * mirror (one from `route.triggers` in config) throws rather than being dropped.
 */
import type { RouteResult } from "../../packages/core/src/route/route.js"
import { QUESTIONS, TRIGGER_QUESTIONS } from "./policy.js"

/** One value per question: a choice's key, a score's level, or a noul's 0–1. */
export type CurrentAnswers = Record<string, string | number>

export function toAnswerSpace(output: RouteResult): CurrentAnswers {
  if (typeof output?.matched !== "boolean") throw new Error("matched is not a boolean")
  const fired = new Set<string>()
  for (const t of output.triggers ?? []) {
    if (!Object.hasOwn(QUESTIONS, t.name)) throw new Error(`trigger "${t.name}" is not a question`)
    fired.add(t.name)
  }
  // A regex is certain either way, so each noul is 1 or 0. `hint` is whether a
  // hint is shown (after the opt-out veto); a trigger is whether its pattern
  // fired, vetoed or not.
  const answers: CurrentAnswers = { hint: output.matched ? 1 : 0 }
  for (const name of TRIGGER_QUESTIONS) answers[name] = fired.has(name) ? 1 : 0
  return answers
}
