/**
 * Decision-model policy for `route-hint`, generated by system1 `adopt` from
 * `.system1/specs/route-hint.yaml`, against the workspace's own
 * `@garygentry/system1-core` (this repo's M11 dogfood: plan item 9).
 *
 * It sits in front of the regex prompt router (`packages/core/src/route/route.ts`,
 * decision 0018) and is inert until you switch it on twice: `enabled: true`
 * where you call it, and the `EGRESS` line below. Until both are on, every call
 * takes the existing path. Any call the model can't answer well enough also
 * takes the existing path, with a reason code to log.
 *
 * It is a shadow, run from source by vitest and tsx, never cut over: the
 * routing hook ships inside the bundled `decide` CLI, where the module lock
 * can't hold (docs/runtime.md, "The module lock and your build"), and 0018
 * promises the hook sends nothing. Nothing in packages/ imports this file.
 */
import {
  type Answers,
  createPolicyRuntime,
  type PolicyRuntime,
  type QuestionSet,
  type ReasonCode,
} from "@garygentry/system1-core/runtime"
import {
  BUILTIN_IGNORE,
  BUILTIN_TRIGGERS,
  DEFAULT_MESSAGE,
  type RouteMatch,
  type RouteResult,
} from "../../packages/core/src/route/route.js"

// Runtime egress for this module. `adopt` writes "off" and never anything else.
// Changing it to "on" is your decision, made in reviewed code: it lets this
// module send prompt text to OpenRouter's decision model. Nothing else turns it on.
export const EGRESS: "on" | "off" = "off" // system1: runtime egress (only you switch this on)

/** Measured spend a UTC day before every call takes the existing path (`budget`). */
export const MAX_USD_PER_DAY = 1.0
/** The decision model this module was generated and recorded against. */
export const MODEL = "typesafe/jev-1.13"
/** The spec's name: the fixture namespace its recorded answers live under. */
export const SPEC = "route-hint"

// The spec's questions, copied verbatim. Recorded answers are keyed on them, so
// an edit here needs fresh fixtures (`decide spec check route-hint --live`).
// policy.test.ts checks they match the spec file.
export const QUESTIONS: QuestionSet = {
  hint: {
    type: "noul",
    instructions:
      "The user's message asks the agent for closed verdicts over text that it would otherwise read and judge piece by piece: a label, yes/no or score for each of many items (tickets, reviews, commits, failures, log lines, rows, commands, files), the one best match out of a long list of candidates (packages, files, helpers, options), one verdict per rule or acceptance criterion over a diff, a log or test output, or a verdict on each step or command before an action that is hard to undo.",
    criteria: {
      true: "The message asks for such verdicts, over a batch of items, a choice among many candidates, each rule or criterion held against evidence, or each step of something about to run.",
      false:
        "The message asks the agent to do something (write, fix, edit, run, commit, rename, explain, summarise), asks for an exact fact (a count, a list of matches, a date, whether a command succeeded), or asks one question about one small thing.",
    },
  },
  "batch-judgement": {
    type: "noul",
    instructions:
      "The message asks for a verdict, label or score on each of many items of text, or asks which of many items match a description.",
    criteria: {
      true: 'It names a batch (a file of tickets, reviews, commits, failures, rows or commands, or "every", "each", "all of") and asks for a judgement on each item.',
      false:
        "It asks about one item, asks for an exact list or count, or asks for no judgement at all.",
    },
  },
  "pick-from-many": {
    type: "noul",
    instructions:
      "The message asks for the single best match out of many candidates (packages, libraries, files, helpers, options) listed somewhere.",
    criteria: {
      true: "There are many candidates and the user wants one of them picked.",
      false: "There are only a few options, or no pick is asked for.",
    },
  },
  "criteria-check": {
    type: "noul",
    instructions:
      "The message asks whether something meets a set of rules, criteria, requirements, a checklist, a policy or conventions.",
    criteria: {
      true: "A rule set is named or listed, and the user wants to know whether the work, diff or output meets it.",
      false:
        "No rule set is involved, or the user asks to write or change the rules rather than check against them.",
    },
  },
  "done-check": {
    type: "noul",
    instructions:
      "The message asks whether a task or change is done, complete, or ready to merge, ship or commit, judged from evidence such as a diff, test output or a task file.",
    criteria: {
      true: "The user asks for a verdict on whether the work is finished or ready.",
      false:
        "The user asks for work to be done, or asks a factual question such as whether a command succeeded.",
    },
  },
  "gate-check": {
    type: "noul",
    instructions:
      "Before an action that is hard to undo (commit, merge, push, deploy, release, running a script), the message asks whether it is safe, destructive or against the rules.",
    criteria: {
      true: "An action is about to happen and the user wants a safety or rules verdict first.",
      false: "No such action is pending, or no verdict is asked for before it.",
    },
  },
}

/** The questions that mirror route.ts's built-in triggers, one each, by the same name. */
export const TRIGGER_QUESTIONS = BUILTIN_TRIGGERS.map((t) => t.name)

// The spec's `policy.thresholds`. A `hint` between the two bars is not acted
// on: the call takes the existing path (the regex's answer).
export const THRESHOLDS = {
  /** `hint` at or above this hints (the spec's 0.7: a wrong hint derails a turn). */
  hintAtLeast: 0.7,
  /** `hint` at or below this stays quiet. */
  noHintAtMost: 0.3,
  /** A trigger question at or above this is named in the hint. */
  triggerAtLeast: 0.7,
} as const

/** What the model sees for one prompt: the prompt itself, as the hook receives it. */
export function toState(prompt: string): string {
  return prompt
}

/** One step of the decision, for a log line or a test. */
export interface TraceStep {
  step: string
  detail?: string
}

export type Outcome =
  | { value: RouteResult; by: "model"; trace: TraceStep[] }
  | {
      value: RouteResult
      by: "existing"
      /** Why the model's answer wasn't used. */
      reason: ReasonCode | "disabled" | "below-threshold" | "vetoed"
      detail: string
      trace: TraceStep[]
    }

export interface PolicyOptions {
  /** The app-level switch. False (the default) keeps the existing path for every call. */
  enabled?: boolean
  /** Where the spend ledger and recorded answers live. Without it, spend is counted in memory. */
  root?: string
  /** `replay` answers from `root`'s recorded fixtures and sends nothing: how the tests run. */
  mode?: "live" | "replay"
  timeoutMs?: number
  /** For tests: a stand-in for the runtime. */
  runtime?: Pick<PolicyRuntime, "decide">
}

/**
 * Route a prompt with the decision model, falling back to `existing` (the
 * regex router) when the policy is off, the prompt opts out in words, or the
 * model's answer doesn't clear the spec's thresholds. It never throws because
 * of the model; `existing` may.
 */
export async function routeHint(
  prompt: string,
  existing: (prompt: string) => RouteResult | Promise<RouteResult>,
  options: PolicyOptions = {},
): Promise<Outcome> {
  const trace: TraceStep[] = []
  const fallBack = async (
    reason: ReasonCode | "disabled" | "below-threshold" | "vetoed",
    detail: string,
  ): Promise<Outcome> => {
    trace.push({ step: "existing", detail: reason })
    return { value: await existing(prompt), by: "existing", reason, detail, trace }
  }
  if (options.enabled !== true) return fallBack("disabled", "the policy is not enabled")
  // An opt-out is an exact phrase, so it is matched here, as route.ts does,
  // and never costs a call.
  if (BUILTIN_IGNORE.some((p) => new RegExp(p, "i").test(prompt)))
    return fallBack("vetoed", "the prompt says not to use System 1")
  const mode = options.mode ?? "live"
  // The runtime refuses too; checking here keeps an off module from loading anything.
  if (mode === "live" && EGRESS !== "on")
    return fallBack("egress-off", "runtime egress is off (this module's EGRESS line)")

  const runtime = options.runtime ?? runtimeFor(options)
  const result = await runtime.decide({
    questions: QUESTIONS,
    state: toState(prompt),
    namespace: SPEC,
  })
  // `=== false`, not `!`: it narrows the union without strictNullChecks too.
  let answers: Answers
  if (result.ok === false) {
    trace.push({ step: "model", detail: result.detail })
    // The runtime calls a result undecided when any question is. Only `hint`
    // decides; the trigger questions only name the hint, so a flat one there
    // just goes unnamed.
    const decidedHint =
      result.reason === "undecided" && result.answers && !result.undecided?.includes("hint")
    if (!decidedHint || !result.answers) return fallBack(result.reason, result.detail)
    answers = result.answers
  } else {
    trace.push({ step: "model", detail: result.source })
    answers = result.answers
  }
  const value = fromAnswers(answers, trace)
  return value ? { value, by: "model", trace } : fallBack("below-threshold", traceLine(trace))
}

/**
 * The model's answers as the router's result, or `undefined` when `hint`
 * sits between the bars. Each check is added to `trace`.
 */
export function fromAnswers(answers: Answers, trace: TraceStep[] = []): RouteResult | undefined {
  const hint = answers.hint
  if (hint?.type !== "noul") {
    trace.push({ step: "answers", detail: "missing or of the wrong type" })
    return undefined
  }
  let hints: boolean | undefined
  if (hint.noul >= THRESHOLDS.hintAtLeast) hints = true
  else if (hint.noul <= THRESHOLDS.noHintAtMost) hints = false
  trace.push({
    step: "hint",
    detail: `${hint.noul.toFixed(2)} → ${hints === undefined ? "between the bars" : hints}`,
  })
  if (hints === undefined) return undefined
  if (!hints) return { enabled: true, matched: false, triggers: [] }
  const triggers: RouteMatch[] = []
  for (const name of TRIGGER_QUESTIONS) {
    const a = answers[name]
    if (a?.type === "noul" && a.noul >= THRESHOLDS.triggerAtLeast)
      triggers.push({ name, source: "builtin", text: `model ${a.noul.toFixed(2)}` })
  }
  trace.push({ step: "triggers", detail: triggers.map((t) => t.name).join(", ") || "none" })
  // A hint with no trigger over its bar still names where it came from.
  const names = triggers.map((t) => t.name).join(", ") || "hint"
  return {
    enabled: true,
    matched: true,
    triggers,
    message: DEFAULT_MESSAGE.replaceAll("{triggers}", names),
  }
}

const traceLine = (trace: TraceStep[]) =>
  trace.map((t) => (t.detail ? `${t.step}: ${t.detail}` : t.step)).join("; ")

// One runtime per root and mode, so the daily cap counts every call in the process.
const runtimes = new Map<string, PolicyRuntime>()
function runtimeFor(options: PolicyOptions): PolicyRuntime {
  const mode = options.mode ?? "live"
  const key = JSON.stringify([options.root ?? null, mode, options.timeoutMs ?? null])
  let runtime = runtimes.get(key)
  if (!runtime) {
    runtime = createPolicyRuntime({
      maxUsdPerDay: MAX_USD_PER_DAY,
      model: MODEL,
      mode,
      ...(options.root ? { root: options.root } : {}),
      ...(options.timeoutMs ? { timeoutMs: options.timeoutMs } : {}),
      // The runtime reads this file's EGRESS line too: both must say on. A
      // bundle without this source on disk needs "bundled", your edit.
      module: import.meta.url,
      // Last, so nothing spread above can override it.
      egress: EGRESS,
    })
    runtimes.set(key, runtime)
  }
  return runtime
}
