/**
 * Offline tests for the `route-hint` policy module, generated by system1
 * `adopt`. They answer from the spec's recorded fixtures (replay): nothing is
 * sent, and no key or grant is needed.
 *
 * Record fresh fixtures with `decide spec check route-hint --live` after
 * changing the questions or the states below; the states here are the spec's
 * examples, so their recorded answers are what replay serves.
 */
import assert from "node:assert/strict"
import {
  chmodSync,
  cpSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import { afterAll, describe, it } from "vitest"
import { parse } from "yaml"
import { ROUTE_DEFAULTS, type RouteResult, route } from "../../packages/core/src/route/route.js"
import { samples } from "./capture.js"
import { grantProblems } from "./grants.js"
import { toAnswerSpace } from "./mapping.js"
import {
  EGRESS,
  fromAnswers,
  type Outcome,
  QUESTIONS,
  routeHint,
  SPEC,
  TRIGGER_QUESTIONS,
} from "./policy.js"
import { captureShadow } from "./shadow.js"

/** The repo's `.system1` directory, which holds `fixtures/route-hint/`. */
const SYSTEM1_DIR = fileURLToPath(new URL("../../.system1", import.meta.url))
/** The module files `adopt` wrote, checked for a grant below. */
const MODULE_FILES = [
  "policy.ts",
  "mapping.ts",
  "shadow.ts",
  "grants.ts",
  "capture.ts",
  "evaluate.ts",
  "policy.test.ts",
].map((name) => fileURLToPath(new URL(`./${name}`, import.meta.url)))

// The spec's examples, verbatim: their answers are recorded.
const BATCH = "Go through alerts.jsonl and tell me which of the 120 alerts are false positives."
const DO = "Fix the failing test in src/billing/charge.test.ts and commit it."
const PICK =
  "We have about 90 helper functions in src/util. Which single one should I use to retry a fetch with backoff?"
const OPT_OUT =
  "Without using decide, read reviews.jsonl and label each review as positive or negative."
/** The comment on the one grant line, assembled so this file carries none. */
const MARKER = ["system1", ": runtime ", "egr", "ess"].join("")

const NEVER_RECORDED = "No fixture holds this prompt."

const EXISTING: RouteResult = { enabled: true, matched: false, triggers: [] }
const existing = () => EXISTING

/** Tests that run in live mode are skipped once EGRESS is on, so a test never sends. */
const LIVE_SKIP = EGRESS !== "off"

const scratch: string[] = []
function tempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "system1-policy-"))
  scratch.push(dir)
  return dir
}
afterAll(() => {
  for (const dir of scratch) {
    makeWritable(dir)
    rmSync(dir, { recursive: true, force: true })
  }
})

/** A copy of the recorded fixtures in a directory with no `.git`, made read-only. */
function readOnlyRoot(): string {
  const root = join(tempDir(), "system1")
  cpSync(join(SYSTEM1_DIR, "fixtures", SPEC), join(root, "fixtures", SPEC), { recursive: true })
  for (const path of walk(root).reverse())
    chmodSync(path, statSync(path).isDirectory() ? 0o555 : 0o444)
  return root
}

function walk(dir: string): string[] {
  return [
    dir,
    ...readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
      e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)],
    ),
  ]
}

function makeWritable(dir: string) {
  for (const path of walk(dir)) chmodSync(path, statSync(path).isDirectory() ? 0o755 : 0o644)
}

const fellBack = (outcome: Outcome, reason: string) => {
  assert.equal(outcome.by, "existing", JSON.stringify(outcome))
  assert.deepEqual(outcome.value, EXISTING)
  if (outcome.by === "existing") assert.equal(outcome.reason, reason)
}

describe("runtime egress", () => {
  // When you switch EGRESS on, change this expectation in the same reviewed edit.
  it("is off as generated", () => {
    assert.equal(EGRESS, "off")
  })

  it("has no grant in the module's source, in any spelling", () => {
    const policy = readFileSync(MODULE_FILES[0] as string, "utf8")
    assert.equal(policy.split("\n").filter((line) => line.includes(MARKER)).length, 1)
    for (const file of MODULE_FILES)
      assert.deepEqual(grantProblems(readFileSync(file, "utf8")), [], file)
  })

  it("catches the grants it scans for", () => {
    // Assembled, so this file holds none of them.
    const [E, e] = ["EG" + "RESS", "egr" + "ess"]
    for (const bad of [
      `export const ${E}: "on" | "off" = "o${"n"}" // system1${": runtime "}${e}`,
      `${E} = 'o${"n"}'`,
      `${E}=process.env.X`,
      `${E} = "off" && "on" // system1${": runtime "}${e}`,
      `import { ${E} } from "./settings.ts"\nf({ ${e}: ${E} })`,
      `options.${e} = "on"`,
      `${e}: true,`,
      `${e}Consent: true`,
    ])
      assert.notDeepEqual(grantProblems(bad), [], bad)
  })
})

describe("the spec", () => {
  it("has the module's questions, verbatim", () => {
    const spec = parse(readFileSync(join(SYSTEM1_DIR, "specs", `${SPEC}.yaml`), "utf8")) as {
      questions: unknown
    }
    assert.deepEqual(spec.questions, QUESTIONS)
  })

  it("mirrors every built-in route trigger with a question", () => {
    for (const name of TRIGGER_QUESTIONS) assert.ok(Object.hasOwn(QUESTIONS, name), name)
  })
})

describe("inert by default", () => {
  it("takes the existing path when not enabled", async () => {
    let calls = 0
    const outcome = await routeHint(BATCH, () => {
      calls++
      return EXISTING
    })
    fellBack(outcome, "disabled")
    assert.equal(calls, 1)
  })

  it.skipIf(LIVE_SKIP)("takes the existing path when enabled but EGRESS is off", async () => {
    fellBack(await routeHint(BATCH, existing, { enabled: true }), "egress-off")
  })

  it("never asks the model about a prompt that opts out in words", async () => {
    let asked = false
    const runtime = {
      decide: async () => {
        asked = true
        throw new Error("not reached")
      },
    }
    fellBack(
      await routeHint(OPT_OUT, existing, { enabled: true, mode: "replay", runtime }),
      "vetoed",
    )
    assert.equal(asked, false)
  })

  it("honours the user's route config before any call", async () => {
    const runtime = {
      decide: async () => {
        throw new Error("not reached")
      },
    }
    const base = { enabled: true, mode: "replay" as const, runtime }
    fellBack(
      await routeHint(BATCH, existing, { ...base, config: { ...ROUTE_DEFAULTS, enabled: false } }),
      "disabled",
    )
    fellBack(
      await routeHint(BATCH, existing, {
        ...base,
        config: { ...ROUTE_DEFAULTS, ignore: ["alerts\\.jsonl"] },
      }),
      "vetoed",
    )
    fellBack(
      await routeHint(BATCH, existing, { ...base, config: { ...ROUTE_DEFAULTS, builtin: false } }),
      "disabled",
    )
    fellBack(
      await routeHint(BATCH, existing, {
        ...base,
        config: { ...ROUTE_DEFAULTS, disable: [...TRIGGER_QUESTIONS] },
      }),
      "disabled",
    )
  })

  it("throws on a bad route config before any call, whatever the model would say", async () => {
    let asked = false
    const runtime = {
      decide: async () => {
        asked = true
        throw new Error("not reached")
      },
    }
    const base = { enabled: true, mode: "replay" as const, runtime }
    for (const config of [
      { ...ROUTE_DEFAULTS, disable: ["nope"] },
      { ...ROUTE_DEFAULTS, triggers: [{ name: "mine", pattern: "(" }] },
      { ...ROUTE_DEFAULTS, ignore: ["("] },
    ])
      await assert.rejects(routeHint(BATCH, existing, { ...base, config }), /route/)
    assert.equal(asked, false)
  })
})

describe("answers from recorded fixtures (replay)", () => {
  const replay = { enabled: true, mode: "replay" as const, root: SYSTEM1_DIR }

  it("hints, naming the triggers over their bar", async () => {
    const outcome = await routeHint(BATCH, existing, replay)
    assert.equal(outcome.by, "model", JSON.stringify(outcome))
    assert.equal(outcome.value.matched, true)
    assert.deepEqual(
      outcome.value.triggers.map((t) => t.name),
      ["batch-judgement"],
    )
    assert.match(outcome.value.message ?? "", /\(batch-judgement\)/)
  })

  it("stays quiet on a do-something prompt", async () => {
    const outcome = await routeHint(DO, existing, replay)
    assert.equal(outcome.by, "model")
    assert.deepEqual(outcome.value, { enabled: true, matched: false, triggers: [] })
  })

  it("keeps the regex's answer when hint sits between the bars", async () => {
    // Recorded at 0.64.
    fellBack(await routeHint(PICK, existing, replay), "below-threshold")
  })

  it("falls back on a provider error: no recorded answer", async () => {
    fellBack(await routeHint(NEVER_RECORDED, existing, replay), "provider-error")
  })

  it("falls back when the state is refused as too large", async () => {
    fellBack(await routeHint("word ".repeat(40_000), existing, replay), "refused")
  })

  it.skipIf(LIVE_SKIP)("works from a directory with no .git and a read-only root", async () => {
    const cwd = process.cwd()
    process.chdir(tempDir())
    try {
      const root = readOnlyRoot()
      const answered = await routeHint(BATCH, existing, { ...replay, root })
      assert.equal(answered.by, "model")
      fellBack(await routeHint(BATCH, existing, { enabled: true, root }), "egress-off")
    } finally {
      process.chdir(cwd)
    }
  })
})

describe("thresholds", () => {
  const noul = (v: number) => ({ type: "noul" as const, noul: v })
  const answers = (hint: number, trigger = 0.1) => ({
    hint: noul(hint),
    ...Object.fromEntries(TRIGGER_QUESTIONS.map((n) => [n, noul(trigger)])),
  })
  const answered = (hint: number, trigger?: number) => ({
    enabled: true,
    mode: "replay" as const,
    runtime: {
      decide: async () => ({
        ok: true as const,
        source: "replay" as const,
        answers: answers(hint, trigger),
        usage: { input_tokens: 0, output_tokens: 0, cost: 0 },
        latencyMs: 1,
        ledger: "memory" as const,
      }),
    },
  })
  const undecided = (names: string[], hint: number) => ({
    enabled: true,
    mode: "replay" as const,
    runtime: {
      decide: async () => ({
        ok: false as const,
        reason: "undecided" as const,
        detail: `undecided: ${names.join(", ")}`,
        answers: answers(hint, 0.5),
        undecided: names,
        ledger: "memory" as const,
      }),
    },
  })

  it("falls back when hint itself is undecided", async () => {
    fellBack(await routeHint(BATCH, existing, undecided(["hint"], 0.5)), "undecided")
  })

  it("acts on a decided hint when only trigger questions are undecided", async () => {
    const outcome = await routeHint(BATCH, existing, undecided(["gate-check"], 0.9))
    assert.equal(outcome.by, "model")
    assert.equal(outcome.value.matched, true)
    assert.match(outcome.value.message ?? "", /\(hint\)/)
  })

  it("falls back between the bars", async () => {
    fellBack(await routeHint(BATCH, existing, answered(0.5)), "below-threshold")
  })

  it("acts at the bars, and traces each branch", async () => {
    const yes = await routeHint(BATCH, existing, answered(0.7, 0.7))
    assert.equal(yes.by, "model")
    assert.equal(yes.value.triggers.length, TRIGGER_QUESTIONS.length)
    assert.deepEqual(
      yes.trace.map((t) => t.step),
      ["model", "hint", "triggers"],
    )
    const no = await routeHint(BATCH, existing, answered(0.3, 0.9))
    assert.equal(no.by, "model")
    assert.equal(no.value.matched, false)
  })

  it("names only the triggers the config leaves on, in the config's message", async () => {
    const outcome = await routeHint(BATCH, existing, {
      ...answered(0.9, 0.9),
      config: { ...ROUTE_DEFAULTS, disable: ["gate-check"], message: "use ask ({triggers})" },
    })
    assert.equal(outcome.by, "model")
    assert.ok(!outcome.value.triggers.some((t) => t.name === "gate-check"))
    assert.equal(outcome.value.triggers.length, TRIGGER_QUESTIONS.length - 1)
    assert.match(outcome.value.message ?? "", /^use ask \(batch-judgement/)
  })

  it("keeps the existing path when only disabled triggers would name the hint", async () => {
    const only = (name: string) => ({
      enabled: true,
      mode: "replay" as const,
      config: { ...ROUTE_DEFAULTS, disable: ["gate-check"] },
      runtime: {
        decide: async () => ({
          ok: true as const,
          source: "replay" as const,
          answers: {
            hint: noul(0.9),
            ...Object.fromEntries(TRIGGER_QUESTIONS.map((n) => [n, noul(n === name ? 0.9 : 0.1)])),
          },
          usage: { input_tokens: 0, output_tokens: 0, cost: 0 },
          latencyMs: 1,
          ledger: "memory" as const,
        }),
      },
    })
    fellBack(await routeHint(BATCH, existing, only("gate-check")), "below-threshold")
    assert.equal((await routeHint(BATCH, existing, only("batch-judgement"))).by, "model")
  })

  it("records the mode when it acts on a result the runtime called undecided", async () => {
    const outcome = await routeHint(BATCH, existing, undecided(["gate-check"], 0.9))
    assert.match(outcome.trace[0]?.detail ?? "", /^replay: undecided/)
  })

  it("reads answers of the wrong shape as below the bar", () => {
    assert.equal(fromAnswers({}), undefined)
  })
})

describe("output → answer mapping", () => {
  it("maps the regex's result into the answer space", () => {
    const mapped = toAnswerSpace(route(BATCH, ROUTE_DEFAULTS))
    assert.equal(mapped.hint, 1)
    assert.equal(mapped["batch-judgement"], 1)
    assert.deepEqual(Object.keys(mapped).sort(), Object.keys(QUESTIONS).sort())
  })

  it("maps a vetoed prompt as no hint, with its triggers still fired", () => {
    const mapped = toAnswerSpace(route(OPT_OUT, ROUTE_DEFAULTS))
    assert.equal(mapped.hint, 0)
    assert.equal(mapped["batch-judgement"], 1)
  })

  it("refuses a trigger the question set doesn't mirror", () => {
    assert.throws(() =>
      toAnswerSpace({
        enabled: true,
        matched: true,
        triggers: [{ name: "mine", source: "config", text: "" }],
      }),
    )
    assert.throws(() => toAnswerSpace({ triggers: [] } as unknown as RouteResult))
  })
})

describe("shadow capture", () => {
  it("doesn't let a torn last line swallow the next row", async () => {
    const file = join(tempDir(), "captured.jsonl")
    writeFileSync(file, '{"id": "t0", "sta')
    await captureShadow([{ id: "t1", prompt: BATCH }], async () => ({ output: EXISTING }), {
      file,
      warn: () => {},
    })
    assert.equal(JSON.parse(readFileSync(file, "utf8").split("\n")[1] as string).id, "t1")
  })

  it("writes one row per prompt with a measured zero cost, and warns", async () => {
    const file = join(tempDir(), "captured.jsonl")
    const warnings: string[] = []
    const summary = await captureShadow(
      [
        { id: "a", prompt: BATCH },
        { id: "b", prompt: DO },
      ],
      async (prompt) => ({ output: route(prompt, ROUTE_DEFAULTS), usage: { cost: 0 } }),
      { file, warn: (m) => warnings.push(m) },
    )
    assert.equal(summary.written, 2)
    assert.match(warnings.join("\n"), /raw inputs/)
    const rows = readFileSync(file, "utf8")
      .trim()
      .split("\n")
      .map((l) => JSON.parse(l))
    assert.equal(rows[0].state, BATCH)
    assert.equal(rows[0].current.hint, 1)
    assert.equal(rows[1].current.hint, 0)
    assert.deepEqual(rows[0].usage, { cost: 0 })
  })

  it("samples every ask prompt of the routing evals once, labelled by polarity", () => {
    const all = samples()
    assert.equal(new Set(all.map((s) => s.id)).size, all.length)
    assert.ok(all.length >= 72)
    for (const s of all) assert.equal(s.hint, s.id.includes(":pos:") ? 1 : 0)
  })
})
