/**
 * The runtime for adopted code ([0020](../../../../plans/decisions/0020-runtime-consent-for-adopted-code.md)):
 * what a policy module generated by `adopt` calls in the user's application.
 *
 * - **The grant is the caller's `egress` argument,** which a generated module
 *   takes from its one marked line. Nothing here reads consent from the repo
 *   config or the environment.
 * - **The environment is explicit.** No walking up from `cwd`: `root` names
 *   where the spend ledger and fixtures live. Without a writable `root`, spend
 *   is counted in memory for the process.
 * - **It never throws.** Every result that isn't a model answer is a fallback
 *   with a reason code the app can log or count, so "never called" is visible.
 */
import { join } from "node:path"
import { unquoteKey } from "../config/load.js"
import { createDecider, type DecisionResult, type Unsaved } from "../decide.js"
import { isDecisionsError } from "../errors.js"
import { FixtureStore } from "../fixtures/store.js"
import {
  DEFAULT_MODEL_ID,
  type ModelProfile,
  projectCost,
  resolveProfile,
} from "../model/profiles.js"
import type { Answers, QuestionSet, State, Usage } from "../model/types.js"
import { prepareState } from "../prepare.js"
import { SpendLedger } from "../run/spend.js"
import { createOpenRouterTransport } from "../transport/openrouter.js"

/** Why a call fell back to the existing mechanism. Stable: apps count these. */
export const REASON_CODES = [
  "egress-off",
  "undecided",
  "provider-error",
  "refused",
  "budget",
  "timeout",
  "no-key",
  "engine-unavailable",
  "internal",
] as const
export type ReasonCode = (typeof REASON_CODES)[number]

/** The ledger tag on every runtime call, so its spend is summed apart. */
export const RUNTIME_TAG = "runtime"

export interface PolicyRuntimeOptions {
  /**
   * The grant. A generated module passes its marked `EGRESS` line here, and
   * `adopt` only ever writes `"off"`. Replay needs no grant: it sends nothing.
   */
  egress: "on" | "off"
  /**
   * Measured spend a day (UTC) before every call falls back with `budget`. A
   * call goes when today's spend plus its projected cost fits, so the last one
   * can pass the cap by the difference between its measured and projected cost.
   */
  maxUsdPerDay: number
  /** Where `usage.jsonl` and `fixtures/` live. Absent or unwritable: memory only. */
  root?: string
  /** Default `typesafe/jev-1.13`. */
  model?: string
  /** `live` (default) calls the model; `replay` answers from `root`'s fixtures, offline. */
  mode?: "live" | "replay"
  /** Default: `OPENROUTER_API_KEY` from the environment. A key alone never grants egress. */
  apiKey?: string
  /** Per attempt. Default 5 s. */
  timeoutMs?: number
  endpoint?: string
  fetch?: typeof fetch
  now?: () => Date
}

export interface PolicyRequest {
  questions: QuestionSet
  state: State
  /** Fixture namespace: the spec's name. */
  namespace: string
}

interface Common {
  /** Where this call's spend was counted. */
  ledger: "file" | "memory"
}

export type PolicyResult =
  | (Common & {
      ok: true
      source: "live" | "replay"
      answers: Answers
      usage: Usage
      latencyMs: number
    })
  | (Common & {
      ok: false
      reason: ReasonCode
      /** One line for a log. Never the state or the key. */
      detail: string
      /** Present when the model answered but too flatly to act on. */
      answers?: Answers
      undecided?: string[]
    })

export interface PolicyRuntime {
  decide(request: PolicyRequest): Promise<PolicyResult>
  /** Measured spend so far today (UTC), as the cap sees it. */
  spentToday(): number
}

export function createPolicyRuntime(options: PolicyRuntimeOptions): PolicyRuntime {
  const now = options.now ?? (() => new Date())
  const mode = options.mode ?? "live"
  const cap = options.maxUsdPerDay
  const env = process.env
  let apiKey: string | undefined
  try {
    apiKey = options.apiKey ?? unquoteKey(env.OPENROUTER_API_KEY)?.value
  } catch {
    apiKey = undefined
  }
  let profile: ModelProfile | undefined
  let profileError: string | undefined
  try {
    profile = resolveProfile(options.model ?? DEFAULT_MODEL_ID)
  } catch (error) {
    profileError = error instanceof Error ? error.message : String(error)
  }

  // The file ledger, until a write fails; then memory for the rest of the process.
  let ledger: SpendLedger | undefined = options.root
    ? new SpendLedger(join(options.root, "usage.jsonl"))
    : undefined
  const fixtures = options.root ? new FixtureStore(join(options.root, "fixtures")) : undefined
  let memory = { day: "", usd: 0 }
  const today = () => now().toISOString().slice(0, 10)
  const spentToday = (): number => {
    const day = today()
    if (memory.day !== day) memory = { day, usd: 0 }
    if (!ledger) return memory.usd
    try {
      const fromFile = ledger.summary({
        since: new Date(`${day}T00:00:00.000Z`),
        tag: RUNTIME_TAG,
      }).cost
      return Math.max(fromFile, memory.usd)
    } catch {
      return memory.usd
    }
  }
  const where = (): Common["ledger"] => (ledger ? "file" : "memory")
  const fallback = (reason: ReasonCode, detail: string, extra = {}): PolicyResult => ({
    ok: false,
    reason,
    detail,
    ledger: where(),
    ...extra,
  })

  return {
    spentToday,
    async decide({ questions, state, namespace }) {
      try {
        if (!profile) return fallback("internal", profileError ?? "no model profile")
        if (mode === "live" && options.egress !== "on")
          return fallback("egress-off", "runtime egress is off (the module's EGRESS line)")
        if (mode === "live" && !apiKey) return fallback("no-key", "OPENROUTER_API_KEY is not set")
        if (mode === "replay" && !fixtures)
          return fallback("internal", "replay needs a root with recorded fixtures")

        let prepared: ReturnType<typeof prepareState>
        try {
          prepared = prepareState(state, { questions, profile, id: namespace })
        } catch (error) {
          return isDecisionsError(error) && error.code === "state-too-large"
            ? fallback("refused", "the state is too large for the model")
            : fallback("internal", firstLine(error))
        }

        if (mode === "live") {
          const projected = projectCost(profile, 1, prepared.tokens)
          const spent = spentToday()
          if (spent + projected > cap)
            return fallback(
              "budget",
              `today's spend $${spent.toFixed(4)} would pass the $${cap} cap (maxUsdPerDay)`,
            )
        }

        const decider = createDecider({
          profile,
          egressConsent: options.egress === "on",
          mode,
          ...(mode === "live" && apiKey
            ? {
                transport: createOpenRouterTransport({
                  apiKey,
                  ...(options.endpoint ? { endpoint: options.endpoint } : {}),
                  ...(options.timeoutMs ? { timeoutMs: options.timeoutMs } : {}),
                  ...(options.fetch ? { fetch: options.fetch } : {}),
                }),
              }
            : {}),
          ...(fixtures ? { fixtures } : {}),
          ...(ledger ? { ledger } : {}),
          tag: RUNTIME_TAG,
          now,
        })
        let result: DecisionResult
        try {
          result = await decider.decide({ state: prepared.state, questions, namespace })
        } catch (error) {
          return fallback(reasonFor(error), firstLine(error))
        }
        count(result.usage.cost, result.unsaved)
        if (result.undecided.length > 0)
          return fallback("undecided", `undecided: ${result.undecided.join(", ")}`, {
            answers: result.answers,
            undecided: result.undecided,
          })
        return {
          ok: true,
          source: result.source,
          answers: result.answers,
          usage: result.usage,
          latencyMs: result.latencyMs,
          ledger: where(),
        }
      } catch (error) {
        return fallback("internal", firstLine(error))
      }
    },
  }

  /** Always in memory; the file too, until a write fails. */
  function count(usd: number, unsaved: Unsaved[] | undefined): void {
    spentToday()
    memory.usd += usd
    if (unsaved?.some((u) => u.what === "ledger")) ledger = undefined
  }
}

function reasonFor(error: unknown): ReasonCode {
  if ((error as { name?: string })?.name === "AbortError") return "timeout"
  if (!isDecisionsError(error)) return "internal"
  switch (error.code) {
    case "provider-unreachable":
      return /timed out|timeout/i.test(error.message) ? "timeout" : "provider-error"
    case "provider-http":
    case "malformed-response":
    case "replay-miss":
    case "unknown-model":
      return "provider-error"
    case "state-too-large":
    case "egress-refused":
      return "refused"
    case "no-key":
      return "no-key"
    case "budget-exceeded":
      return "budget"
    default:
      return "internal"
  }
}

/** Never the state: error messages from this layer name codes and limits, not content. */
function firstLine(error: unknown): string {
  const text = error instanceof Error ? error.message : String(error)
  return (text.split("\n")[0] ?? "").slice(0, 200)
}
