/**
 * The runtime for adopted code ([0020](../../../../plans/decisions/0020-runtime-consent-for-adopted-code.md)):
 * what a policy module generated by `adopt` calls in the user's application.
 *
 * - **The grant is the caller's `egress` argument,** which a generated module
 *   takes from its one marked line. Nothing here reads consent from a config
 *   file or the environment, and nothing here loads the config.
 * - **The environment is explicit.** No walking up from `cwd`: `root` names
 *   where the spend ledger and fixtures live. Without a writable `root`, spend
 *   is counted in memory for the process.
 * - **It never throws or rejects.** Every result that isn't a model answer is
 *   a fallback with a reason code the app can log or count.
 */
import { closeSync, fstatSync, openSync, readSync } from "node:fs"
import { join } from "node:path"
import { unquoteKey } from "../config/key.js"
import { createDecider, type DecisionResult } from "../decide.js"
import { scrubText } from "../egress/scrub.js"
import { isDecisionsError } from "../errors.js"
import { FixtureStore } from "../fixtures/store.js"
import {
  DEFAULT_MODEL_ID,
  type ModelProfile,
  projectCost,
  resolveProfile,
} from "../model/profiles.js"
import type { Answers, QuestionSet, State, Usage } from "../model/types.js"
import { prepareState } from "../prepare.js"
import { SpendLedger } from "../run/spend.js"
import { createOpenRouterTransport, DEFAULT_TIMEOUT_MS } from "../transport/openrouter.js"

/** Why a call fell back to the existing mechanism. Stable: apps count these. */
export const REASON_CODES = [
  "egress-off",
  "undecided",
  "provider-error",
  "refused",
  "budget",
  "timeout",
  "no-key",
  "engine-unavailable",
  "internal",
] as const
export type ReasonCode = (typeof REASON_CODES)[number]

/** The ledger tag on every runtime call, so its spend is summed apart. */
export const RUNTIME_TAG = "runtime"

export interface PolicyRuntimeOptions {
  /**
   * The grant, exactly `"on"` or `"off"`. A generated module passes its marked
   * `EGRESS` line here, and `adopt` only ever writes `"off"`. Anything but
   * `"on"` is off. Replay needs no grant: it sends nothing.
   */
  egress: "on" | "off"
  /**
   * Measured spend a UTC day before every call falls back with `budget`: a
   * finite number, at least 0. Each call reserves its projected cost first, so
   * concurrent calls can't race past it; a call's measured cost can still pass
   * the cap by the difference. A cost the provider doesn't report counts at
   * its projection.
   */
  maxUsdPerDay: number
  /**
   * Where `usage.jsonl` and `fixtures/` live. Absent or unwritable: memory
   * only. With a writable root, today's spend there (every runtime line, from
   * any process sharing the root) is read once at start, so the cap survives
   * a restart.
   */
  root?: string
  /** Default `typesafe/jev-1.13`. */
  model?: string
  /** `live` (default) calls the model; `replay` answers from `root`'s fixtures, offline, and writes nothing. */
  mode?: "live" | "replay"
  /** Default: `OPENROUTER_API_KEY` from the environment. A key alone never grants egress. */
  apiKey?: string
  /** The whole call, retries included. Default 5000 ms. */
  timeoutMs?: number
  endpoint?: string
  fetch?: typeof fetch
  now?: () => Date
}

export interface PolicyRequest {
  questions: QuestionSet
  state: State
  /** Fixture namespace: the spec's name. */
  namespace: string
}

interface Common {
  /** Where this call's spend was counted. */
  ledger: "file" | "memory"
}

export type PolicyResult =
  | (Common & {
      ok: true
      source: "live" | "replay"
      answers: Answers
      usage: Usage
      latencyMs: number
    })
  | (Common & {
      ok: false
      reason: ReasonCode
      /** One line for a log, built from codes and limits: never the state, the key or a response body. */
      detail: string
      /** With `undecided`: the answers, for the log. */
      answers?: Answers
      undecided?: string[]
    })

export interface PolicyRuntime {
  decide(request: PolicyRequest): Promise<PolicyResult>
  /** Spend so far today (UTC), as the cap sees it: measured, plus calls in flight at their projection. */
  spentToday(): number
}

interface Setup {
  profile: ModelProfile
  mode: "live" | "replay"
  cap: number
  timeoutMs: number
  apiKey?: string
}

export function createPolicyRuntime(options: PolicyRuntimeOptions): PolicyRuntime {
  const opts: Partial<PolicyRuntimeOptions> = options ?? {}
  const now = () => {
    try {
      const at = (opts.now ?? (() => new Date()))()
      return Number.isNaN(at.getTime()) ? new Date() : at
    } catch {
      return new Date()
    }
  }
  const setup = validate(opts)
  const root = typeof opts.root === "string" && opts.root ? opts.root : undefined
  const fixtures = root ? new FixtureStore(join(root, "fixtures")) : undefined
  // Written until a write fails; then memory only for the rest of the process.
  let ledger: SpendLedger | undefined =
    root && typeof setup !== "string" && setup.mode === "live"
      ? new SpendLedger(join(root, "usage.jsonl"))
      : undefined

  // Today's spend: seeded once a day from the file, then kept in memory.
  let day = { key: "", usd: 0 }
  const rollDay = () => {
    const key = now().toISOString().slice(0, 10)
    if (day.key === key) return
    day = { key, usd: ledger ? todayFromFile(ledger.file, `${key}T00:00:00.000Z`) : 0 }
  }
  const spentToday = () => {
    rollDay()
    return day.usd
  }
  const fallback = (reason: ReasonCode, detail: string, extra = {}): PolicyResult => ({
    ok: false,
    reason,
    detail,
    ledger: ledger ? "file" : "memory",
    ...extra,
  })

  async function decide(request: PolicyRequest): Promise<PolicyResult> {
    if (typeof setup === "string") return fallback("internal", setup)
    const { profile, mode, cap, timeoutMs, apiKey } = setup
    const { questions, state, namespace } = request ?? ({} as PolicyRequest)
    if (mode === "live" && opts.egress !== "on")
      return fallback("egress-off", "runtime egress is off (the module's EGRESS line)")
    if (mode === "live" && !apiKey)
      return fallback("no-key", "OPENROUTER_API_KEY is missing or malformed")
    if (mode === "replay" && !fixtures)
      return fallback("internal", "replay needs a root with recorded fixtures")

    let prepared: ReturnType<typeof prepareState>
    try {
      prepared = prepareState(state, { questions, profile, id: String(namespace) })
    } catch (error) {
      return isDecisionsError(error) && error.code === "state-too-large"
        ? fallback("refused", "the state is too large for the model")
        : fallback("internal", describe(error))
    }

    // Reserve the projection before any await, so concurrent calls see it.
    const projected = mode === "live" ? projectCost(profile, 1, prepared.tokens) : 0
    if (mode === "live") {
      const spent = spentToday()
      if (spent + projected > cap)
        return fallback(
          "budget",
          `today's spend $${spent.toFixed(4)} would pass the $${cap} cap (maxUsdPerDay)`,
        )
      day.usd += projected
    }
    const deadline = AbortSignal.timeout(timeoutMs)
    let result: DecisionResult
    try {
      result = await createDecider({
        profile,
        egressConsent: opts.egress === "on",
        mode,
        ...(mode === "live" && apiKey
          ? {
              transport: createOpenRouterTransport({
                apiKey,
                timeoutMs,
                ...(opts.endpoint ? { endpoint: opts.endpoint } : {}),
                ...(opts.fetch ? { fetch: opts.fetch } : {}),
              }),
            }
          : {}),
        ...(fixtures ? { fixtures } : {}),
        ...(ledger ? { ledger } : {}),
        tag: RUNTIME_TAG,
        now,
      }).decide({ state: prepared.state, questions, namespace, signal: deadline })
    } catch (error) {
      // Nothing measured came back. The projection stays counted: the provider
      // may have been paid (a timeout after it answered), and over-counting is
      // the safe side of a cap.
      if (deadline.aborted) return fallback("timeout", `no answer within ${timeoutMs} ms`)
      return fallback(reasonFor(error), describe(error))
    }
    if (mode === "live") {
      // Swap the reservation for what was measured; unreported cost stays projected.
      const measured = result.usage.reported === false ? projected : result.usage.cost
      if (Number.isFinite(measured)) day.usd += measured - projected
      if (result.unsaved?.some((u) => u.what === "ledger")) ledger = undefined
    }
    if (result.undecided.length > 0)
      return fallback("undecided", `undecided: ${result.undecided.join(", ")}`, {
        answers: result.answers,
        undecided: result.undecided,
      })
    return {
      ok: true,
      source: result.source,
      answers: result.answers,
      usage: result.usage,
      latencyMs: result.latencyMs,
      ledger: ledger ? "file" : "memory",
    }
  }

  return {
    spentToday: () => {
      try {
        return spentToday()
      } catch {
        return day.usd
      }
    },
    decide: async (request) => {
      try {
        return await decide(request)
      } catch (error) {
        return fallback("internal", describe(error))
      }
    },
  }
}

/** The options, checked once: a setup, or why every call will fall back as `internal`. */
function validate(opts: Partial<PolicyRuntimeOptions>): Setup | string {
  const cap = opts.maxUsdPerDay
  if (typeof cap !== "number" || !Number.isFinite(cap) || cap < 0)
    return "maxUsdPerDay must be a finite number, at least 0"
  const mode = opts.mode ?? "live"
  if (mode !== "live" && mode !== "replay") return `mode must be "live" or "replay"`
  const timeoutMs = opts.timeoutMs ?? DEFAULT_TIMEOUT_MS
  if (typeof timeoutMs !== "number" || !Number.isFinite(timeoutMs) || timeoutMs <= 0)
    return "timeoutMs must be a number above 0"
  if (opts.root !== undefined && typeof opts.root !== "string") return "root must be a path"
  let profile: ModelProfile
  try {
    profile = resolveProfile(opts.model ?? DEFAULT_MODEL_ID)
  } catch {
    return `unknown model "${String(opts.model)}"`
  }
  let apiKey: string | undefined
  try {
    apiKey = unquoteKey(opts.apiKey ?? process.env.OPENROUTER_API_KEY)?.value
  } catch {
    apiKey = undefined // malformed: reported as no-key, never echoed
  }
  return { profile, mode, cap, timeoutMs, ...(apiKey ? { apiKey } : {}) }
}

/**
 * Today's runtime spend in a ledger file, read backwards from the end until a
 * line is older than today: the file is append-only and in time order, so a
 * long history costs nothing. Only finite costs count.
 */
function todayFromFile(file: string, since: string): number {
  let fd: number
  try {
    fd = openSync(file, "r")
  } catch {
    return 0
  }
  try {
    let position = fstatSync(fd).size
    let carry = ""
    let usd = 0
    const chunk = Buffer.alloc(64 * 1024)
    while (position > 0) {
      const size = Math.min(chunk.length, position)
      position -= size
      readSync(fd, chunk, 0, size, position)
      const lines = (chunk.subarray(0, size).toString("utf8") + carry).split("\n")
      carry = position > 0 ? (lines.shift() ?? "") : ""
      for (const line of lines.reverse()) {
        const entry = parse(line)
        if (!entry) continue
        if (entry.ts < since) return usd
        if (entry.tag === RUNTIME_TAG && Number.isFinite(entry.cost)) usd += entry.cost
      }
    }
    const first = parse(carry)
    if (first && first.ts >= since && first.tag === RUNTIME_TAG && Number.isFinite(first.cost))
      usd += first.cost
    return usd
  } catch {
    return 0
  } finally {
    closeSync(fd)
  }
}

function parse(line: string): { ts: string; tag?: string; cost: number } | undefined {
  if (!line.trim()) return undefined
  try {
    const e = JSON.parse(line) as { ts?: unknown; tag?: unknown; cost?: unknown }
    if (typeof e.ts !== "string") return undefined
    return {
      ts: e.ts,
      ...(typeof e.tag === "string" ? { tag: e.tag } : {}),
      cost: typeof e.cost === "number" ? e.cost : Number.NaN,
    }
  } catch {
    return undefined
  }
}

function reasonFor(error: unknown): ReasonCode {
  if (!isDecisionsError(error)) return "internal"
  switch (error.code) {
    case "provider-unreachable":
    case "provider-http":
    case "malformed-response":
    case "replay-miss":
      return "provider-error"
    case "state-too-large":
    case "egress-refused":
      return "refused"
    case "no-key":
      return "no-key"
    case "budget-exceeded":
      return "budget"
    default:
      return "internal"
  }
}

/**
 * A detail safe for any log: a provider error by its code and status only (its
 * message quotes the endpoint's response body, which may echo the state), a
 * replay miss in the runtime's own words, and anything else scrubbed.
 */
function describe(error: unknown): string {
  if (isDecisionsError(error)) {
    if (error.code === "replay-miss") return "no recorded answer for this state (replay)"
    if (error.code === "provider-http") {
      const status = (error as { status?: number }).status
      return `provider-http${status ? ` ${status}` : ""}`
    }
    if (error.code === "provider-unreachable" || error.code === "malformed-response")
      return error.code
  }
  const text = error instanceof Error ? error.message : String(error)
  return scrubText(
    (text.split("\n")[0] ?? "").replace(/Bearer\s+\S+/gi, "Bearer [REDACTED]"),
  ).slice(0, 200)
}
