/**
 * The runtime for adopted code ([0020](../../../../plans/decisions/0020-runtime-consent-for-adopted-code.md)):
 * what a policy module generated by `adopt` calls in the user's application.
 *
 * - **The grant is the caller's `egress` argument,** which a generated module
 *   takes from its one marked line. Nothing here reads consent from a config
 *   file or the environment, and nothing here loads the config.
 * - **The environment is explicit.** No walking up from `cwd`: `root` names
 *   where the spend ledger and fixtures live. Without a writable `root`, spend
 *   is counted in memory for the process.
 * - **It never throws or rejects.** Every result that isn't a model answer is
 *   a fallback with a reason code the app can log or count.
 */
import { closeSync, fstatSync, openSync, readSync } from "node:fs"
import { join } from "node:path"
import { unquoteKey } from "../config/key.js"
import { createDecider, type DecisionResult } from "../decide.js"
import { scrubText } from "../egress/scrub.js"
import { isDecisionsError, ProviderError } from "../errors.js"
import { FixtureStore } from "../fixtures/store.js"
import {
  DEFAULT_MODEL_ID,
  type ModelProfile,
  projectCost,
  resolveProfile,
} from "../model/profiles.js"
import type { Answers, QuestionSet, State, Usage } from "../model/types.js"
import { prepareState } from "../prepare-state.js"
import { SpendLedger } from "../run/spend.js"
import { createOpenRouterTransport, DEFAULT_TIMEOUT_MS } from "../transport/openrouter.js"

/** Why a call fell back to the existing mechanism. Stable: apps count these. */
export const REASON_CODES = [
  "egress-off",
  "undecided",
  "provider-error",
  "refused",
  "budget",
  "timeout",
  "no-key",
  "engine-unavailable",
  "internal",
] as const
export type ReasonCode = (typeof REASON_CODES)[number]

/** The ledger tag on every runtime call, so its spend is summed apart. */
export const RUNTIME_TAG = "runtime"

export interface PolicyRuntimeOptions {
  /**
   * The grant, exactly `"on"` or `"off"`. A generated module passes its marked
   * `EGRESS` line here, and `adopt` only ever writes `"off"`. Anything but
   * `"on"` is off. Replay needs no grant: it sends nothing.
   */
  egress: "on" | "off"
  /**
   * Measured spend a UTC day before every call falls back with `budget`: a
   * finite number, at least 0. Each call reserves its projected cost first, so
   * concurrent calls can't race past it; a call's measured cost can still pass
   * the cap by the difference. A cost the provider doesn't report counts at
   * its projection.
   */
  maxUsdPerDay: number
  /**
   * Where `usage.jsonl` and `fixtures/` live. Absent or unwritable: memory
   * only. With a writable root, today's spend there (every runtime line, from
   * any process sharing the root) is read once at start, so the cap survives
   * a restart.
   */
  root?: string
  /** Default `typesafe/jev-1.13`. */
  model?: string
  /** `live` (default) calls the model; `replay` answers from `root`'s fixtures, offline, and writes nothing. */
  mode?: "live" | "replay"
  /** Default: `OPENROUTER_API_KEY` from the environment. A key alone never grants egress. */
  apiKey?: string
  /** The whole call, retries included. Default 5000 ms. */
  timeoutMs?: number
  endpoint?: string
  fetch?: typeof fetch
  now?: () => Date
}

export interface PolicyRequest {
  questions: QuestionSet
  state: State
  /** Fixture namespace: the spec's name. */
  namespace: string
}

interface Common {
  /** Where this call's spend was counted. */
  ledger: "file" | "memory"
}

export type PolicyResult =
  | (Common & {
      ok: true
      source: "live" | "replay"
      answers: Answers
      usage: Usage
      latencyMs: number
    })
  | (Common & {
      ok: false
      reason: ReasonCode
      /** One line for a log, built from codes and limits: never the state, the key or a response body. */
      detail: string
      /** With `undecided`: the answers, for the log. */
      answers?: Answers
      undecided?: string[]
    })

export interface PolicyRuntime {
  decide(request: PolicyRequest): Promise<PolicyResult>
  /** Spend so far today (UTC), as the cap sees it: measured, plus calls in flight at their projection. */
  spentToday(): number
}

interface Setup {
  profile: ModelProfile
  mode: "live" | "replay"
  cap: number
  timeoutMs: number
  apiKey?: string
}

export function createPolicyRuntime(options: PolicyRuntimeOptions): PolicyRuntime {
  const opts: Partial<PolicyRuntimeOptions> = options ?? {}
  const now = () => {
    try {
      const at = (opts.now ?? (() => new Date()))()
      return Number.isNaN(at.getTime()) ? new Date() : at
    } catch {
      return new Date()
    }
  }
  const setup = validate(opts)
  const root = typeof opts.root === "string" && opts.root ? opts.root : undefined
  const fixtures = root ? new FixtureStore(join(root, "fixtures")) : undefined
  // The runtime writes its own spend lines (what it counted, not only what was
  // reported), until a write fails; then memory only for the rest of the process.
  let ledger: SpendLedger | undefined =
    root && typeof setup !== "string" && setup.mode === "live"
      ? new SpendLedger(join(root, "usage.jsonl"))
      : undefined
  if (ledger?.unwritable()) ledger = undefined

  // Today's spend: seeded once a day from the file, then kept in memory.
  let day = { key: "", usd: 0 }
  const rollDay = () => {
    const key = now().toISOString().slice(0, 10)
    if (day.key === key) return
    day = { key, usd: ledger ? todayFromFile(ledger.file, `${key}T00:00:00.000Z`) : 0 }
  }
  /** Count `usd` against the day the call reserved on, and record it. */
  const settle = (dayKey: string, delta: number, entry?: { usd: number; usage?: Usage }) => {
    if (day.key === dayKey && Number.isFinite(delta)) day.usd += delta
    if (!entry || !ledger || typeof setup === "string") return
    try {
      ledger.append({
        ts: now().toISOString(),
        tag: RUNTIME_TAG,
        model: setup.profile.id,
        source: "live",
        calls: 1,
        input_tokens: entry.usage?.input_tokens ?? 0,
        output_tokens: entry.usage?.output_tokens ?? 0,
        cost: entry.usd,
        ...(entry.usage?.reported === false || !entry.usage ? { reported: false } : {}),
      })
    } catch {
      ledger = undefined
    }
  }
  const spentToday = () => {
    rollDay()
    return day.usd
  }
  const fallback = (reason: ReasonCode, detail: string, extra = {}): PolicyResult => ({
    ok: false,
    reason,
    detail,
    ledger: ledger ? "file" : "memory",
    ...extra,
  })

  async function decide(request: PolicyRequest): Promise<PolicyResult> {
    if (typeof setup === "string") return fallback("internal", setup)
    const { profile, mode, cap, timeoutMs, apiKey } = setup
    const { questions, state, namespace } = request ?? ({} as PolicyRequest)
    if (mode === "live" && opts.egress !== "on")
      return fallback("egress-off", "runtime egress is off (the module's EGRESS line)")
    if (mode === "live" && !apiKey)
      return fallback("no-key", "OPENROUTER_API_KEY is missing or malformed")
    if (mode === "replay" && !fixtures)
      return fallback("internal", "replay needs a root with recorded fixtures")

    let prepared: ReturnType<typeof prepareState>
    try {
      prepared = prepareState(state, { questions, profile, id: String(namespace) })
    } catch (error) {
      return isDecisionsError(error) && error.code === "state-too-large"
        ? fallback("refused", "the state is too large for the model")
        : fallback("internal", describe(error))
    }

    // Reserve the projection before any await, so concurrent calls see it.
    const projected = mode === "live" ? projectCost(profile, 1, prepared.tokens) : 0
    if (mode === "live") spentToday() // rolls the day over first
    const dayKey = day.key
    if (mode === "live") {
      if (day.usd + projected > cap)
        return fallback(
          "budget",
          `today's spend $${day.usd.toFixed(4)} would pass the $${cap} cap (maxUsdPerDay)`,
        )
      day.usd += projected
    }
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), timeoutMs)
    const timedOut = new Promise<"timeout">((resolve) =>
      controller.signal.addEventListener("abort", () => resolve("timeout"), { once: true }),
    )
    let result: DecisionResult | "timeout"
    try {
      const call = createDecider({
        profile,
        egressConsent: opts.egress === "on",
        mode,
        ...(mode === "live" && apiKey
          ? {
              transport: createOpenRouterTransport({
                apiKey,
                timeoutMs,
                ...(opts.endpoint ? { endpoint: opts.endpoint } : {}),
                ...(opts.fetch ? { fetch: opts.fetch } : {}),
              }),
            }
          : {}),
        ...(fixtures ? { fixtures } : {}),
        now,
      }).decide({ state: prepared.state, questions, namespace, signal: controller.signal })
      // The deadline wins even over a fetch that ignores the abort.
      result = await Promise.race([call, timedOut])
    } catch (error) {
      if (controller.signal.aborted) result = "timeout"
      else {
        // The transport says what a failure may have cost (`spent`): the cost a
        // 200 reported, plus the projection for each attempt billed unreported.
        // No `spent` on a provider error means nothing ran. Anything else keeps
        // the projection, the safe side of a cap; recorded so a restart counts it.
        if (mode === "live") {
          const counted =
            error instanceof ProviderError
              ? error.spent
                ? knownCost(error.spent.usage) + projected * error.spent.uncounted
                : 0
              : projected
          settle(dayKey, counted - projected, counted > 0 ? { usd: counted } : undefined)
        }
        return fallback(reasonFor(error), describe(error))
      }
    } finally {
      clearTimeout(timer)
    }
    if (result === "timeout") {
      if (mode === "live") settle(dayKey, 0, { usd: projected })
      return fallback("timeout", `no answer within ${timeoutMs} ms`)
    }
    if (mode === "live") {
      // Swap the reservation for what was counted: the reported cost, never
      // below zero, plus the projection for each attempt billed unreported (a
      // custom transport that doesn't say counts an unreported answer as one).
      const unreported = result.uncountedAttempts ?? (result.usage.reported === false ? 1 : 0)
      const counted = knownCost(result.usage) + projected * unreported
      settle(dayKey, counted - projected, { usd: counted, usage: result.usage })
    }
    if (result.undecided.length > 0)
      return fallback("undecided", `undecided: ${result.undecided.join(", ")}`, {
        answers: result.answers,
        undecided: result.undecided,
      })
    return {
      ok: true,
      source: result.source,
      answers: result.answers,
      usage: result.usage,
      latencyMs: result.latencyMs,
      ledger: ledger ? "file" : "memory",
    }
  }

  return {
    spentToday: () => {
      try {
        return spentToday()
      } catch {
        return day.usd
      }
    },
    decide: async (request) => {
      try {
        return await decide(request)
      } catch (error) {
        return fallback("internal", describe(error))
      }
    },
  }
}

/** The options, checked once: a setup, or why every call will fall back as `internal`. */
function validate(opts: Partial<PolicyRuntimeOptions>): Setup | string {
  const cap = opts.maxUsdPerDay
  if (typeof cap !== "number" || !Number.isFinite(cap) || cap < 0)
    return "maxUsdPerDay must be a finite number, at least 0"
  const mode = opts.mode ?? "live"
  if (mode !== "live" && mode !== "replay") return `mode must be "live" or "replay"`
  const timeoutMs = opts.timeoutMs ?? DEFAULT_TIMEOUT_MS
  if (
    typeof timeoutMs !== "number" ||
    !Number.isFinite(timeoutMs) ||
    timeoutMs <= 0 ||
    timeoutMs > 600_000
  )
    return "timeoutMs must be a number above 0, at most 600000"
  if (opts.root !== undefined && typeof opts.root !== "string") return "root must be a path"
  let profile: ModelProfile
  try {
    profile = resolveProfile(opts.model ?? DEFAULT_MODEL_ID)
  } catch {
    return `unknown model "${String(opts.model)}"`
  }
  if (profile.transport !== "openrouter-decisions")
    return `${profile.id} is an emulated baseline; the runtime uses decision models only`
  let apiKey: string | undefined
  try {
    apiKey = unquoteKey(opts.apiKey ?? process.env.OPENROUTER_API_KEY)?.value
  } catch {
    apiKey = undefined // malformed: reported as no-key, never echoed
  }
  return { profile, mode, cap, timeoutMs, ...(apiKey ? { apiKey } : {}) }
}

/** How far out of order a shared ledger's lines may be (clock skew between processes). */
const SKEW_MS = 60 * 60 * 1000

/**
 * Today's runtime spend in a ledger file, read backwards from the end until a
 * line is more than an hour older than today: the file is append-only and in
 * roughly time order, so a long history costs nothing. Timestamps are compared
 * as instants, not text. Only finite, non-negative costs count.
 */
function todayFromFile(file: string, sinceIso: string): number {
  const since = Date.parse(sinceIso)
  let fd: number
  try {
    fd = openSync(file, "r")
  } catch {
    return 0
  }
  try {
    let position = fstatSync(fd).size
    let carry = ""
    let usd = 0
    const chunk = Buffer.alloc(64 * 1024)
    while (position > 0) {
      const size = Math.min(chunk.length, position)
      position -= size
      readSync(fd, chunk, 0, size, position)
      const lines = (chunk.subarray(0, size).toString("utf8") + carry).split("\n")
      carry = position > 0 ? (lines.shift() ?? "") : ""
      for (const line of lines.reverse()) {
        const entry = parse(line)
        if (!entry) continue
        if (entry.at < since - SKEW_MS) return usd
        if (entry.at >= since && entry.tag === RUNTIME_TAG) usd += entry.cost
      }
    }
    const first = parse(carry)
    if (first && first.at >= since && first.tag === RUNTIME_TAG) usd += first.cost
    return usd
  } catch {
    return 0
  } finally {
    closeSync(fd)
  }
}

function parse(line: string): { at: number; tag?: string; cost: number } | undefined {
  if (!line.trim()) return undefined
  try {
    const e = JSON.parse(line) as { ts?: unknown; tag?: unknown; cost?: unknown }
    const at = typeof e.ts === "string" ? Date.parse(e.ts) : Number.NaN
    if (!Number.isFinite(at)) return undefined
    const cost = typeof e.cost === "number" && Number.isFinite(e.cost) ? Math.max(0, e.cost) : 0
    return { at, ...(typeof e.tag === "string" ? { tag: e.tag } : {}), cost }
  } catch {
    return undefined
  }
}

function reasonFor(error: unknown): ReasonCode {
  if (!isDecisionsError(error)) return "internal"
  switch (error.code) {
    case "provider-unreachable":
    case "provider-http":
    case "malformed-response":
    case "replay-miss":
      return "provider-error"
    case "state-too-large":
    case "egress-refused":
      return "refused"
    case "no-key":
      return "no-key"
    case "budget-exceeded":
      return "budget"
    default:
      return "internal"
  }
}

/**
 * A detail safe for any log: a provider error by its code and status only (its
 * message quotes the endpoint's response body, which may echo the state), a
 * replay miss in the runtime's own words, and anything else scrubbed.
 */
function describe(error: unknown): string {
  if (isDecisionsError(error)) {
    if (error.code === "replay-miss") return "no recorded answer for this state (replay)"
    if (error.code === "provider-http") {
      const status = (error as { status?: number }).status
      return `provider-http${status ? ` ${status}` : ""}`
    }
    if (error.code === "provider-unreachable" || error.code === "malformed-response")
      return error.code
  }
  // Only this engine's own messages; another error (a JSON.parse of a corrupt
  // fixture, say) can quote the content it choked on, so only its name is kept.
  if (!isDecisionsError(error)) return error instanceof Error ? error.name : "error"
  const text = error.message
  return scrubText(
    (text.split("\n")[0] ?? "").replace(/Bearer\s+\S+/gi, "Bearer [REDACTED]"),
  ).slice(0, 200)
}

/** The cost a usage block reported, never below zero; zero when none was. */
function knownCost(usage: Usage): number {
  return Number.isFinite(usage.cost) ? Math.max(0, usage.cost) : 0
}
