"""The grant scan for this module's tests, generated by system1 `adopt`, and
the same scan `pnpm validate` runs over adopt's templates (0020).

`adopt` only ever writes the marked line set to "off"; turning it on is the
user's edit. This is an allowlist for the name, read one line at a time:
- the marked line is a `const` (TS) or `Final` (Python) set to "off";
- every other use of the name in code is a comparison, an import, a
  `(name, "off")` assertion, or the runtime's option given exactly the name as
  the last property, closing its object, in the file that declares it;
- a Unicode line separator is refused, since TypeScript ends a line there.

Comment lines and string contents are skipped. It reads text, not what runs: a
computed key or code it doesn't parse can still pass it, so the user's review
of the diff is the control. `decide runtime` also reads the marked line from
the module file, so both must say on. The words are assembled so this file
carries no grant of its own.
"""

from __future__ import annotations

import re

E, e = "EG" + "RESS", "egr" + "ess"
MARKER = "".join(["system1", ": runtime ", e])

_OFF_LINE = re.compile(
    r"^(?:(?:export\s+)?const\s+" + E
    + r"""\s*(?::\s*[\w.[\]|,"' ]+?\s*)?=\s*(["'])off\1\s*(?:(?:as|satisfies)\s+[\w.]+\s*)?;?\s*//|"""
    + E
    + r"""\s*:\s*Final\s*=\s*(["'])off\2\s*#)\s*"""
    + MARKER
)
_NAME = re.compile(r"\b" + E + r"\b")
_WORD = re.compile(r"\b" + e + r"\b(?!-)")
_ONE_LINE_IMPORT = re.compile(
    r"^\s*(?:import\s*(?:type\s*)?\{[^}]*\}\s*from\s|from\s+[\w.]+\s+import\s+[\w\s,]*$)"
)
_GIVEN_BEFORE = re.compile(r"\b" + e + r"\s*:\s*$")
_CLOSES = re.compile(r"^\s*:\s*" + E + r"\s*[})]")
_LAST_LINE = re.compile(r"^\s*:\s*" + E + r"\s*,?\s*$")
_BY_NAME = re.compile(r"""["']""" + e + r"""["']|\.""" + e + r"\b")
_CONSENT = re.compile(e + "Consent", re.IGNORECASE)
_ENV = re.compile(r"process\.env|os\.environ|getenv")
_REFLECTION = re.compile(r"\bsetattr\s*\(|\bglobals\s*\(|\b__dict__\b|Object\.defineProperty|Reflect\.set")
_STRINGS = re.compile(r"""(?<![fF])"(?:[^"\\]|\\.)*"|(?<![fF])'(?:[^'\\]|\\.)*'""")
_ITEM = re.compile(r"^\s*(?:type\s+)?\w+(?:\s+as\s+\w+)?\s*,?\s*$")


def grant_problems(source: str, python: bool = True) -> list[str]:
    """Everything in `source` that could grant runtime egress; `python` for a `.py` file."""
    problems: list[str] = []
    if re.search("[\u2028\u2029]", source):
        problems.append("a Unicode line separator (U+2028/U+2029)")
    lines = re.split("\r\n|[\r\n\u2028\u2029]", source)
    marked = [line for line in lines if MARKER in line]
    if len(marked) > 1:
        problems.append(f"{len(marked)} lines carry the marker, not one")
    declares = len(marked) == 1 and _OFF_LINE.search(marked[0]) is not None
    comment = re.compile(r"^\s*#") if python else re.compile(r"^\s*(?://|/\*|\*)")
    for i, line in enumerate(lines):
        at = f"line {i + 1}"
        if MARKER in line:
            if not _OFF_LINE.search(line):
                problems.append(f'{at}: the marked line isn\'t a constant set to "off"')
            continue
        if comment.search(line):
            continue
        code = _STRINGS.sub('""', line).replace(f"`{E}`", "")
        for m in _NAME.finditer(code):
            before, after = code[: m.start()], code[m.end():]
            allowed = (
                re.match(r"\s*[!=]==?(?!=)", after)
                or re.search(r"[!=]==?\s*$", before)
                or _ONE_LINE_IMPORT.search(code)
                or (re.search(r"\(\s*$", before) and re.match(r'\s*,\s*""\s*\)', after))
                or _in_import_list(lines, i)
                or _GIVEN_BEFORE.search(before)
            )
            if not allowed:
                problems.append(f"{at}: {E} used other than as allowed")
        for m in _WORD.finditer(code):
            rest = code[m.end():]
            if re.match(r"\s*[:=](?!=)", rest):
                following = next((l for l in lines[i + 1:] if l.strip() != ""), "")
                last = _LAST_LINE.match(rest) and re.match(r"\s*\}", following)
                if not _CLOSES.match(rest) and not last:
                    problems.append(f"{at}: the runtime given anything but {E}, last, closing its object")
                elif not declares:
                    problems.append(f"{at}: the runtime given a {E} this file doesn't declare")
            elif re.match(r"\s*[,})]", rest):
                problems.append(f"{at}: the grant passed as a variable")
        if _BY_NAME.search(line):
            problems.append(f"{at}: the grant set by name")
        if _CONSENT.search(line):
            problems.append(f"{at}: a consent option")
        if _REFLECTION.search(code):
            problems.append(f"{at}: a binding set by reflection")
        if _NAME.search(line) and _ENV.search(line):
            problems.append(f"{at}: {E} read from the environment")
    return problems


def _in_import_list(lines: list[str], i: int) -> bool:
    """Is line `i` a bare item of a multi-line import (TS `import {...} from`, Python `from ... import (...)`)?"""
    if not re.match(r"^\s*" + E + r"\s*,?\s*$", lines[i]):
        return False
    start = i - 1
    while start >= 0 and _ITEM.match(lines[start]):
        start -= 1
    end = i + 1
    while end < len(lines) and _ITEM.match(lines[end]):
        end += 1
    open_ = lines[start] if start >= 0 else ""
    close = lines[end] if end < len(lines) else ""
    return bool(
        (re.match(r"^\s*import\s*(?:type\s*)?\{\s*$", open_) and re.match(r"^\s*\}\s*from\s", close))
        or (re.match(r"^\s*from\s+[\w.]+\s+import\s*\(\s*$", open_) and re.match(r"^\s*\)\s*$", close))
    )
