"""The grant scan for this module's tests, generated by system1 `adopt`: the
Python copy of the scan `pnpm validate` runs over adopt's templates (0020).

`adopt` only ever writes the marked line set to "off"; turning it on is the
user's edit. This is an allowlist for the name, read one line at a time:
- the marked line is a `const` (TS) or `Final` (Python) set to "off";
- every other use of the name in code is a comparison, an import, an
  assertion, a read, or the runtime's option given exactly the name, as the
  last property of a `createPolicyRuntime({...})` literal that also names this
  file (`module: import.meta.url`, so the runtime reads the marked line too),
  in the file that declares it;
- a Unicode line separator, or a backslash-u escape in TS code, is refused;
- `--module` is this file, so `decide runtime` reads this file's marked line.

Comments, docstrings and string contents are skipped. It reads text, not what
runs, so the user's review of the diff is the control. `decide runtime` also
reads the marked line from the module file, so both must say on. The words are
assembled so this file carries no grant of its own.
"""

from __future__ import annotations

import re
from typing import Optional

E, e = "EG" + "RESS", "egr" + "ess"
MARKER = "".join(["system1", ": runtime ", e])
CREATE = "createPolicy" + "Runtime"
A = re.ASCII

_SEPARATOR = re.compile("[\u2028\u2029]")
_LINE_END = re.compile("\r\n|[\r\n\u2028\u2029]")
_OFF_LINE = re.compile(
    r"^(?:(?:export\s+)?const\s+" + E
    + r"""\s*(?::\s*[\w.[\]|,"' ]+?\s*)?=\s*(["'])off\1\s*(?:(?:as|satisfies)\s+[\w.]+\s*)?;?\s*//|"""
    + E
    + r"""\s*:\s*(?:typing\.)?Final(?:\[[\w.[\]|,"' ]+\])?\s*=\s*(["'])off\2\s*#)\s*"""
    + MARKER,
    A,
)
_NAME = re.compile(r"\b" + E + r"\b", A)
_WORD = re.compile(r"\b" + e + r"\b(?!-)", A)
_ONE_LINE_IMPORT = re.compile(
    r"^\s*(?:import\s*(?:type\s*)?\{[^}]*\}\s*from\s|from\s+[\w.]+\s+import\s+[\w\s,]*$)", A
)
_GIVEN_BEFORE = re.compile(r"\b" + e + r"\s*:\s*$", A)
_GIVEN = re.compile(r"^\s*:\s*" + E + r"\s*,?\s*(\}\s*\))?", A)
_QUOTED = re.compile(r"""["'`]""" + e + r"""["'`]""", A)
_BY_NAME = re.compile(r"\." + e + r"\b|\b" + e + r"\s*\(", A)
_CONSENT = re.compile(e + "Consent", re.IGNORECASE | A)
_ENV = re.compile(r"process\.env|os\.environ|getenv", A)
_REFLECTION = re.compile(
    r"\bsetattr\s*\(|\bglobals\s*\(|\b__dict__\b|Object\.defineProperty|Reflect\.set", A
)
_CALLS = re.compile(r"\b" + CREATE + r"\s*\(", A)
_OPENS = re.compile(r"\b" + CREATE + r"\s*\(\s*\{", A)
#: Strings, left to right. A template literal keeps only its `${...}` code.
_STRINGS = re.compile(
    "|".join(
        [
            r"`(?:[^`\\]|\\.)*`",
            r'(?<![fF])(?<![fF][rRbB])"(?:[^"\\]|\\.)*"',
            r"(?<![fF])(?<![fF][rRbB])'(?:[^'\\]|\\.)*'",
        ]
    ),
    A,
)
_ITEM = re.compile(r"^\s*(?:type\s+)?\w+(?:\s+as\s+\w+)?\s*,?\s*$", A)


def grant_problems(source: str, python: bool = True) -> list[str]:
    """Everything in `source` that could grant runtime egress; `python` for a `.py` file."""
    problems: list[str] = []
    if _SEPARATOR.search(source):
        problems.append("a Unicode line separator (U+2028/U+2029)")
    lines = _LINE_END.split(source)
    marked = [line for line in lines if MARKER in line]
    if len(marked) > 1:
        problems.append(f"{len(marked)} lines carry the marker, not one")
    declares = len(marked) == 1 and _OFF_LINE.search(marked[0]) is not None
    codes = _code_lines(lines, python)

    def next_code(i: int) -> str:
        return next((c for c in codes[i + 1:] if c.strip() != ""), "")

    def parens(text: str) -> int:
        return text.count("(") - text.count(")")

    # Parentheses still open in the runtime call, from its `(`; 0 outside it.
    depth = 0
    # Whether the open runtime call has named this file (module: import.meta.url).
    call_module = False
    for i, line in enumerate(lines):
        at = f"line {i + 1}"
        if MARKER in line:
            if not _OFF_LINE.search(line):
                problems.append(f'{at}: the marked line isn\'t a constant set to "off"')
            continue
        code = codes[i]
        if code.strip() == "":
            continue
        if not python and "\\u" in code:
            problems.append(f"{at}: a backslash-u escape in code")
        if python and '"--module"' in line and not re.search(r"abspath\(__file__\)", code + next_code(i)):
            problems.append(f"{at}: --module isn't this file (os.path.abspath(__file__))")
        if _CALLS.search(code) and not _OPENS.search(code):
            problems.append(f"{at}: {CREATE} not given an object literal")
        opened = _OPENS.search(code)
        start = 0 if depth > 0 else (opened.start() if opened else -1)
        in_call = start >= 0
        left = depth + parens(code[start:]) if in_call else 0
        if in_call and depth == 0:
            call_module = False
        for m in re.finditer(r"\bmodule\s*:(?!:)", code, A):
            if not in_call:
                continue
            if re.match(r"\s*import\.meta\.url\s*(?:[,})]|$)", code[m.end():], A):
                call_module = True
            else:
                problems.append(f"{at}: the runtime's module given anything but import.meta.url")
        for m in _NAME.finditer(code):
            before, after = code[: m.start()], code[m.end():]
            allowed = (
                re.match(r"\s*[!=]==?(?!=)", after)
                or re.search(r"[!=]==?\s*$", before)
                or _ONE_LINE_IMPORT.search(code)
                or (re.search(r"\(\s*$", before) and re.match(r'\s*(?:\)|,\s*""\s*[,)])', after))
                or (re.search(r"\w\.$", before, A) and not re.match(r"\s*[-+*/|&]?=(?!=)", after))
                or _in_import_list(lines, i)
                or _GIVEN_BEFORE.search(before)
            )
            if not allowed:
                problems.append(f"{at}: {E} used other than as allowed")
        for m in _WORD.finditer(code):
            rest = code[m.end():]
            if re.match(r"\s*[:=](?!=)", rest):
                given = _GIVEN.match(rest)
                tail = rest[given.end():] if given else rest
                # Last in the call's object: the call closes right after it.
                closes = (given is not None and given.group(1) is not None and left == 0) or (
                    tail.strip() == "" and left == 1 and re.match(r"\s*\}\s*\)", next_code(i)) is not None
                )
                if not given or not closes or not in_call:
                    problems.append(f"{at}: the runtime given anything but {E}, last in {CREATE}({{...}})")
                elif not call_module:
                    problems.append(f"{at}: the runtime call doesn't name this file (module: import.meta.url)")
                elif not declares:
                    problems.append(f"{at}: the runtime given a {E} this file doesn't declare")
            elif re.match(r"\s*[,})]", rest):
                problems.append(f"{at}: the grant passed as a variable")
        if _BY_NAME.search(code) or _QUOTED.search(line):
            problems.append(f"{at}: the grant set by name")
        if _CONSENT.search(line):
            problems.append(f"{at}: a consent option")
        if _REFLECTION.search(code):
            problems.append(f"{at}: a binding set by reflection")
        if _NAME.search(line) and _ENV.search(line):
            problems.append(f"{at}: {E} read from the environment")
        depth = max(left, 0)
    return problems


def _code_lines(lines: list[str], python: bool) -> list[str]:
    """Each line as code only: comments removed (block comments tracked across
    lines in TS, docstrings in Python) and string contents blanked."""
    out: list[str] = []
    in_block = False
    in_doc: Optional[str] = None
    for raw in lines:
        line = raw
        if python:
            if in_doc:
                end = line.find(in_doc)
                if end < 0:
                    out.append("")
                    continue
                line = line[end + 3:]
                in_doc = None
            line = re.sub(r'("""|\'\'\')[\s\S]*?\1', '""', line)
            opened = re.search(r'"""|\'\'\'', line)
            if opened:
                in_doc = opened.group(0)
                line = line[: opened.start()]
            line = _STRINGS.sub('""', line).replace(f"`{E}`", "")
            out.append(re.sub(r"#.*$", "", line))
            continue
        if in_block:
            end = line.find("*/")
            if end < 0:
                out.append("")
                continue
            line = line[end + 2:]
            in_block = False

        def blank(m: re.Match[str]) -> str:
            s = m.group(0)
            if s.startswith("`"):
                return " " + " ".join(re.findall(r"\$\{([^}]*)\}", s)) + " "
            return '""'

        line = _STRINGS.sub(blank, line)
        line = re.sub(r"/\*[\s\S]*?\*/", " ", line)
        opened_at = line.find("/*")
        if opened_at >= 0:
            in_block = True
            line = line[:opened_at]
        out.append(re.sub(r"//.*$", "", line))
    return out


def _in_import_list(lines: list[str], i: int) -> bool:
    """Is line `i` a bare item of a multi-line import (TS `import {...} from`, Python `from ... import (...)`)?"""

    def strip(line: str) -> str:
        return re.sub(r"\s*(?://|#).*$", "", line)

    if not re.match(r"^\s*" + E + r"\s*,?\s*$", strip(lines[i]), A):
        return False
    start = i - 1
    while start >= 0 and _ITEM.match(strip(lines[start])):
        start -= 1
    end = i + 1
    while end < len(lines) and _ITEM.match(strip(lines[end])):
        end += 1
    open_ = strip(lines[start]) if start >= 0 else ""
    close = strip(lines[end]) if end < len(lines) else ""
    return bool(
        (re.match(r"^\s*import\s*(?:type\s*)?(?:\w+\s*,\s*)?\{\s*$", open_, A) and re.match(r"^\s*\}\s*from\s", close, A))
        or (re.match(r"^\s*from\s+[\w.]+\s+import\s*\(\s*$", open_, A) and re.match(r"^\s*\)\s*$", close, A))
    )
