"""The existing mechanism's output in the spec's answer space, generated by
system1 `adopt` for `ticket-triage`. The shadow harness writes it as each
captured row's `current`, so `decide compare` can set the existing answers
beside the decision model's, question by question.

Strict, like `compare`'s own reading: a value the question set doesn't offer
raises rather than being guessed into one.
ADOPT: one entry per question in the spec, from the app's own output type.
"""

from __future__ import annotations

from typing import Union

from policy import QUESTIONS, Triage


def to_answer_space(output: Triage) -> dict[str, Union[str, int, float]]:
    """One value per question: a choice's key, a score's level, or a noul's 0-1."""
    if not isinstance(output.urgent, bool):
        raise ValueError("urgent is not a boolean")
    if output.area not in QUESTIONS["area"]["criteria"]:
        raise ValueError(f"area {output.area!r} is not an offered option")
    return {
        # A yes/no mechanism is certain either way, so its noul is 1 or 0.
        "urgent": 1 if output.urgent else 0,
        "area": output.area,
    }
