"""Decision-model policy for `ticket-triage`, generated by system1 `adopt` from
`.system1/specs/ticket-triage.yaml` against `decide` runtime protocol 1.

It sits in front of the existing mechanism and is inert until you switch it on
twice: `enabled=True` where you call it, and the `EGRESS` line below. Until both
are on, every call takes the existing path. Any call the model can't answer well
enough also takes the existing path, with a reason code to log.

Requirements, in the runtime image and in CI: Node 22 or later and the `decide`
CLI on PATH (`npm install -g @garygentry/system1`). Every call starts one
`decide` process, which costs its startup time (tens of milliseconds). The first
call checks the runtime protocol; when `decide` is missing or speaks another
protocol, every call takes the existing path with `engine-unavailable`.
Python 3.9 or later.

ADOPT: every `ADOPT:` comment marks what to change for the repo's own spec,
types and idiom. Keep the `EGRESS` line exactly as it is, set to "off".
"""

from __future__ import annotations

import json
import os
import subprocess
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Final, Literal, Optional

# Runtime egress for this module. `adopt` writes "off" and never anything else.
# Changing it to "on" is your decision, made in reviewed code: it lets this
# module send ticket text to OpenRouter's decision model. Nothing else turns it on.
EGRESS: Final = "off"  # system1: runtime egress (only you switch this on)

#: Measured spend a UTC day before every call takes the existing path (`budget`).
MAX_USD_PER_DAY: Final = 1.0
#: The decision model this module was generated and recorded against.
MODEL: Final = "typesafe/jev-1.13"
#: The spec's name: the fixture namespace its recorded answers live under.
SPEC: Final = "ticket-triage"
#: The `decide runtime` stdin/stdout shape this module speaks.
PROTOCOL: Final = 1
#: The command that runs `decide`. Tests may point it elsewhere.
DECIDE: list[str] = ["decide"]

# ADOPT: the spec's questions, copied verbatim. Recorded answers are keyed on
# them, so an edit here needs fresh fixtures (`decide spec check <spec> --live`).
QUESTIONS: Final[dict[str, Any]] = {
    "urgent": {
        "type": "noul",
        "instructions": (
            "The ticket reports something that needs a reply within the hour: an outage, "
            "lost data, a security problem, or a customer blocked from working."
        ),
        "criteria": {
            "true": "Something is down, lost, exposed or blocking the customer's work now.",
            "false": "A question, a request, or a problem with a workaround.",
        },
    },
    "area": {
        "type": "choice",
        "instructions": "Which team should handle this ticket?",
        "criteria": {
            "billing": "Charges, invoices, refunds, plans or payment methods.",
            "bug": "The product behaves wrongly or fails.",
            "account": "Sign-in, passwords, users, permissions or settings.",
            "other": "None of the above.",
        },
    },
}

# ADOPT: the spec's `policy.thresholds`. An answer between the two noul bars,
# or a choice below its bar, is not acted on: the call takes the existing path.
URGENT_AT_LEAST: Final = 0.7
NOT_URGENT_AT_MOST: Final = 0.3
AREA_AT_LEAST: Final = 0.6

Area = Literal["billing", "bug", "account", "other"]
AREAS: Final = ("billing", "bug", "account", "other")


# ADOPT: the existing mechanism's input and output types, as the app has them.
@dataclass(frozen=True)
class Ticket:
    subject: str
    body: str


@dataclass(frozen=True)
class Triage:
    urgent: bool
    area: Area


def to_state(ticket: Ticket) -> str:
    """What the model sees for one ticket. The shadow harness captures the same
    state, so `decide compare` judges exactly what this module would send.
    ADOPT: build it from the inputs the existing mechanism reads, and nothing more.
    """
    return f"Subject: {ticket.subject}\n\n{ticket.body}"


@dataclass
class Outcome:
    value: Triage
    #: "model" when the model's answer was used, "existing" otherwise.
    by: Literal["model", "existing"]
    #: Why the model's answer wasn't used: a runtime reason code, "disabled" or "below-threshold".
    reason: Optional[str] = None
    detail: str = ""
    #: Each step of the decision, for a log line or a test.
    trace: list[str] = field(default_factory=list)


#: Runs `decide runtime` with the request on stdin and returns its parsed result.
Engine = Callable[[dict[str, Any], "PolicyOptions"], dict[str, Any]]


@dataclass(frozen=True)
class PolicyOptions:
    #: The app-level switch. False (the default) keeps the existing path for every call.
    enabled: bool = False
    #: Where the spend ledger and recorded answers live. A live call needs a writable one.
    root: Optional[str] = None
    #: True answers from `root`'s recorded fixtures and sends nothing: how the tests run.
    replay: bool = False
    timeout_ms: int = 5000
    #: For tests: a stand-in for spawning `decide runtime`.
    engine: Optional[Engine] = None


def triage(
    ticket: Ticket,
    existing: Callable[[Ticket], Triage],
    options: PolicyOptions = PolicyOptions(),
) -> Outcome:
    """Triage a ticket with the decision model, falling back to `existing` when
    the policy is off or the model's answer doesn't clear the spec's thresholds.
    It never raises because of the model; `existing` may.
    """
    trace: list[str] = []

    def fall_back(reason: str, detail: str) -> Outcome:
        trace.append(f"existing: {reason}")
        return Outcome(existing(ticket), "existing", reason, detail, trace)

    if not options.enabled:
        return fall_back("disabled", "the policy is not enabled")
    # `decide runtime` reads the grant from this file too; both must say on.
    if not options.replay and EGRESS != "on":
        return fall_back("egress-off", "runtime egress is off (this module's EGRESS line)")

    request = {"questions": QUESTIONS, "state": to_state(ticket), "namespace": SPEC}
    result = (options.engine or _spawn)(request, options)
    if result.get("ok") is not True:
        reason = result.get("reason")
        reason = reason if isinstance(reason, str) else "internal"
        trace.append(f"model: {reason}")
        return fall_back(reason, str(result.get("detail", "")))
    trace.append(f"model: {result.get('source')}")
    value = from_answers(result.get("answers"), trace)
    if value is None:
        return fall_back("below-threshold", "; ".join(trace))
    return Outcome(value, "model", trace=trace)


def from_answers(answers: Any, trace: Optional[list[str]] = None) -> Optional[Triage]:
    """The model's answers as the app's output, or None when one doesn't clear
    its threshold. Each check is added to `trace`.
    ADOPT: one branch per question, reading the spec's thresholds.
    """
    trace = trace if trace is not None else []
    urgent = answers.get("urgent") if isinstance(answers, dict) else None
    area = answers.get("area") if isinstance(answers, dict) else None
    if not isinstance(urgent, dict) or urgent.get("type") != "noul":
        trace.append("answers: urgent missing or of the wrong type")
        return None
    if not isinstance(area, dict) or area.get("type") != "choice":
        trace.append("answers: area missing or of the wrong type")
        return None
    noul = urgent.get("noul")
    is_urgent: Optional[bool] = None
    if isinstance(noul, (int, float)):
        if noul >= URGENT_AT_LEAST:
            is_urgent = True
        elif noul <= NOT_URGENT_AT_MOST:
            is_urgent = False
    trace.append(f"urgent: {noul} -> {'between the bars' if is_urgent is None else is_urgent}")
    choice = area.get("choice")
    probabilities = area.get("probabilities")
    p = probabilities.get(choice, 0) if isinstance(probabilities, dict) else 0
    chosen = choice if choice in AREAS and isinstance(p, (int, float)) and p >= AREA_AT_LEAST else None
    trace.append(f"area: {choice} {p} -> {chosen or 'below the bar'}")
    if is_urgent is None or chosen is None:
        return None
    return Triage(is_urgent, chosen)


_protocol_checked: Optional[str] = None  # None: not settled yet; "": fine; otherwise why not


def _engine_problem(timeout_s: float) -> str:
    """Why `decide` can't serve this module, or "" when it can. A definite
    answer (fine, missing, another protocol) is kept for the process; a
    transient failure (a slow start, a failed fork) is tried again next call.
    """
    global _protocol_checked
    if _protocol_checked is not None:
        return _protocol_checked
    try:
        done = subprocess.run(
            [*DECIDE, "runtime", "--protocol"],
            capture_output=True,
            encoding="utf-8",
            timeout=timeout_s,
            check=False,
        )
    except FileNotFoundError:
        _protocol_checked = "decide is not on PATH (npm install -g @garygentry/system1)"
        return _protocol_checked
    except (OSError, subprocess.SubprocessError) as error:
        return f"decide runtime --protocol failed ({type(error).__name__})"
    try:
        protocol = json.loads(done.stdout or "null")
    except ValueError:
        protocol = None
    found = protocol.get("protocol") if isinstance(protocol, dict) else None
    if found is None and isinstance(protocol, dict) and protocol.get("ok") is False:
        # The CLI's error envelope: a `decide` from before `runtime` existed.
        _protocol_checked = "decide has no runtime command (upgrade @garygentry/system1)"
        return _protocol_checked
    if found is None:
        return f"decide runtime --protocol printed nothing usable (exit {done.returncode})"
    _protocol_checked = "" if found == PROTOCOL else f"decide runtime speaks protocol {found}, not {PROTOCOL}"
    return _protocol_checked


def _spawn(request: dict[str, Any], options: PolicyOptions) -> dict[str, Any]:
    """One `decide runtime` call. Every problem is a fallback, never an exception."""
    # The call's own deadline, plus room to start Node, shared with the check.
    deadline = time.monotonic() + options.timeout_ms / 1000 + 10
    problem = _engine_problem(deadline - time.monotonic())
    if problem:
        return {"ok": False, "reason": "engine-unavailable", "detail": problem}
    argv = [
        *DECIDE,
        "runtime",
        "--module",
        os.path.abspath(__file__),
        "--max-usd-per-day",
        str(MAX_USD_PER_DAY),
        "--model",
        MODEL,
        "--timeout-ms",
        str(options.timeout_ms),
    ]
    if options.root:
        argv += ["--root", options.root]
    if options.replay:
        argv.append("--replay")
    try:
        done = subprocess.run(
            argv,
            input=json.dumps(request),
            capture_output=True,
            encoding="utf-8",
            timeout=max(deadline - time.monotonic(), 0.001),
            check=False,
        )
    except subprocess.TimeoutExpired:
        return {"ok": False, "reason": "timeout", "detail": "decide runtime did not answer in time"}
    except (OSError, subprocess.SubprocessError) as error:
        return {"ok": False, "reason": "engine-unavailable", "detail": type(error).__name__}
    try:
        result = json.loads(done.stdout)
    except ValueError:
        return {
            "ok": False,
            "reason": "engine-unavailable",
            "detail": f"decide runtime printed no result (exit {done.returncode})",
        }
    if not isinstance(result, dict):
        return {"ok": False, "reason": "engine-unavailable", "detail": "decide runtime printed no result"}
    return result
