"""Shadow capture for `ticket-triage`, generated by system1 `adopt`. It runs the
existing mechanism over sampled inputs and appends one row per input to
`.system1/compare/ticket-triage/captured.jsonl`:

    {id, state, current, usage?, latencyMs}

`decide compare ticket-triage` then sends each `state` to the decision model and
sets its answers beside `current`. The engine never runs this code.

- The file holds raw inputs (each ticket's text). Keep it out of git:
  `.system1/compare/` belongs in `.gitignore` (compare's recorded answers go there too).
- The existing mechanism runs for real here. If it is a model call, every row
  costs what it costs and sends what it sends, outside system1's checks.
- A row without `usage` means its cost is unknown, never zero.

ADOPT: the sample source and the call to the existing mechanism.
"""

from __future__ import annotations

import json
import math
import os
import sys
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Iterable, Optional

from mapping import to_answer_space
from policy import SPEC, Ticket, Triage, to_state

CAPTURE_FILE = f".system1/compare/{SPEC}/captured.jsonl"


@dataclass
class CurrentRun:
    """What one run of the existing mechanism returned, and what it cost if known."""

    output: Triage
    #: {"cost": USD, "input_tokens"?: n, "output_tokens"?: n}. Leave it out when the cost isn't known.
    usage: Optional[dict[str, Any]] = None


@dataclass
class ShadowSummary:
    file: str
    written: int = 0
    #: Ids already in the file, left as they are.
    skipped: list[str] = field(default_factory=list)
    #: Inputs the existing mechanism, or the mapping, failed on: no row is written.
    failed: list[tuple[str, str]] = field(default_factory=list)


def capture_shadow(
    samples: Iterable[tuple[str, Ticket]],
    current: Callable[[Ticket], CurrentRun],
    file: str = CAPTURE_FILE,
    warn: Callable[[str], None] = lambda message: print(message, file=sys.stderr),
) -> ShadowSummary:
    warn(
        f"system1 shadow: {file} holds raw inputs. "
        "Keep it out of git, and delete it when the comparison is done."
    )
    os.makedirs(os.path.dirname(file) or ".", exist_ok=True)
    seen = _existing_ids(file)
    # A torn last line (a crash mid-write) would swallow the next row.
    if os.path.exists(file) and os.path.getsize(file) > 0:
        with open(file, "rb") as existing:
            existing.seek(-1, os.SEEK_END)
            torn = existing.read(1) != b"\n"
        if torn:
            with open(file, "a", encoding="utf-8") as out:
                out.write("\n")
    summary = ShadowSummary(file)
    for sample_id, ticket in samples:
        if not isinstance(sample_id, str) or not sample_id.strip():
            summary.failed.append((str(sample_id), "an id must be a non-empty string"))
            continue
        if sample_id in seen:
            summary.skipped.append(sample_id)
            continue
        started = time.perf_counter()
        try:
            run = current(ticket)
            # Fractional, to the microsecond: a sub-millisecond mechanism doesn't read 0.
            latency_ms = round((time.perf_counter() - started) * 1000, 3)
            row: dict[str, Any] = {
                "id": sample_id,
                "state": to_state(ticket),
                "current": to_answer_space(run.output),
                "latencyMs": latency_ms,
            }
            usage = _usage(run.usage)
            if usage:
                row["usage"] = usage
            line = json.dumps(row, allow_nan=False)
        except Exception as error:  # noqa: BLE001 - one failed input never stops the capture
            summary.failed.append((sample_id, str(error)))
            continue
        with open(file, "a", encoding="utf-8") as out:
            out.write(line + "\n")
        seen.add(sample_id)
        summary.written += 1
    return summary


def _usage(raw: Any) -> Optional[dict[str, float]]:
    """The cost as `compare` reads it: a finite cost of at least 0, with token
    counts when they are numbers. Anything else means unknown."""
    if not isinstance(raw, dict):
        return None

    def number(value: Any) -> Optional[float]:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            return None
        return float(value) if math.isfinite(value) and value >= 0 else None

    cost = number(raw.get("cost"))
    if cost is None:
        return None
    usage = {"cost": cost}
    for key in ("input_tokens", "output_tokens"):
        count = number(raw.get(key))
        if count is not None:
            usage[key] = count
    return usage


def _existing_ids(file: str) -> set[str]:
    """Ids already captured: `compare` reads a repeated id as a bad line."""
    ids: set[str] = set()
    if not os.path.exists(file):
        return ids
    with open(file, encoding="utf-8") as lines:
        for line in lines:
            try:
                row_id = json.loads(line).get("id")
            except (ValueError, AttributeError):
                continue  # a torn line: compare reports it
            if isinstance(row_id, str):
                ids.add(row_id)
    return ids
