"""Offline tests for the `ticket-triage` policy module, generated by system1
`adopt`. They answer from the spec's recorded fixtures (replay) through
`decide runtime --replay`: nothing is sent, and no key or grant is needed, but
`decide` must be on PATH, as it must be wherever the module runs.

ADOPT: the test runner and paths of the repo. Record fresh fixtures with
`decide spec check ticket-triage --live` after changing the questions or the
states below; the states here are the spec's examples, so their recorded
answers are what replay serves.
"""

from __future__ import annotations

import json
import os
import shutil
import stat
import sys
import tempfile
import unittest
from typing import Any

import policy
from grants import grant_problems
from mapping import to_answer_space
from policy import EGRESS, QUESTIONS, PolicyOptions, Ticket, Triage, triage
from shadow import CurrentRun, capture_shadow

HERE = os.path.dirname(os.path.abspath(__file__))
#: ADOPT: the repo's `.system1` directory, which holds `fixtures/ticket-triage/`.
SYSTEM1_DIR = os.path.join(HERE, "..", ".system1")
#: ADOPT: the module files `adopt` wrote, checked for a grant below.
MODULE_FILES = [
    os.path.join(HERE, name)
    for name in ("policy.py", "mapping.py", "shadow.py", "grants.py", "test_policy.py")
]
#: The comment on the one grant line, assembled so this file carries none.
MARKER = "".join(["system1", ": runtime ", "egr", "ess"])

# ADOPT: the spec's examples, as tickets. The first has a recorded answer.
OUTAGE = Ticket(
    subject="Dashboard down for our whole team",
    body="Since 9am every page returns a 500 error and nobody here can work.",
)
NEVER_RECORDED = Ticket(subject="Never recorded", body="No fixture holds this ticket.")

EXISTING = Triage(urgent=False, area="other")

#: Tests that run in live mode are skipped once EGRESS is on, so a test never sends.
LIVE_SKIP = EGRESS != "off"


def existing(_ticket: Ticket) -> Triage:
    return EXISTING


def answered(urgent: float, area: str, p: float) -> PolicyOptions:
    def engine(_request: dict[str, Any], _options: PolicyOptions) -> dict[str, Any]:
        return {
            "ok": True,
            "source": "replay",
            "answers": {
                "urgent": {"type": "noul", "noul": urgent},
                "area": {"type": "choice", "choice": area, "probabilities": {area: p}, "confidence": p},
            },
            "usage": {"input_tokens": 0, "output_tokens": 0, "cost": 0},
            "latencyMs": 1,
            "ledger": "memory",
        }

    return PolicyOptions(enabled=True, replay=True, engine=engine)


class FallsBack(unittest.TestCase):
    def assert_fell_back(self, outcome: policy.Outcome, reason: str) -> None:
        self.assertEqual(outcome.by, "existing", outcome)
        self.assertEqual(outcome.value, EXISTING)
        self.assertEqual(outcome.reason, reason, outcome.detail)


class RuntimeEgress(unittest.TestCase):
    # When you switch EGRESS on, change this expectation in the same reviewed edit.
    def test_is_off_as_generated(self) -> None:
        self.assertEqual(EGRESS, "off")

    def test_no_grant_in_the_module_source(self) -> None:
        with open(MODULE_FILES[0], encoding="utf-8") as f:
            self.assertEqual(sum(MARKER in line for line in f), 1)
        for path in MODULE_FILES:
            with open(path, encoding="utf-8") as f:
                self.assertEqual(grant_problems(f.read()), [], path)

    def test_catches_the_grants_it_scans_for(self) -> None:
        # Assembled, so this file holds none of them.
        big, small = "EG" + "RESS", "egr" + "ess"
        for bad in [
            f'{big}: Final = "o{"n"}"  # system1: runtime {small}',
            f"{big} = 'o{'n'}'",
            f"{big}=process.env.X",
            f'{big} = "off"',
            f'{big}: Final = "off" and "on"  # system1: runtime {small}',
            f'SEND = os.environ.get("X") == "1"\nrun({small}={big} if not SEND else "on")',
            f"from settings import {big}  # system1: runtime {small}",
            f"{big}, other = load()",
            f'o["{small}"] = "on"',
            f'options.{small} = "on"',
            f'{big}: Final = os.environ.get("X", "off")',
            f"{small}: true,",
            f"{small}=grant",
            f"{small}Consent: true",
            f'g = os.environ["{big}"]',
            f"# system1: runtime {small}\n# system1: runtime {small}",
        ]:
            self.assertNotEqual(grant_problems(bad), [], bad)


class Inert(FallsBack):
    def test_existing_path_when_not_enabled(self) -> None:
        calls = []
        outcome = triage(OUTAGE, lambda t: calls.append(t) or EXISTING)
        self.assert_fell_back(outcome, "disabled")
        self.assertEqual(len(calls), 1)

    @unittest.skipIf(LIVE_SKIP, "EGRESS is on: this test would send")
    def test_existing_path_when_enabled_but_egress_off(self) -> None:
        self.assert_fell_back(triage(OUTAGE, existing, PolicyOptions(enabled=True)), "egress-off")


class Replay(FallsBack):
    """Answers from the recorded fixtures, through `decide runtime --replay`."""

    def setUp(self) -> None:
        policy._protocol_checked = None
        self.replay = PolicyOptions(enabled=True, replay=True, root=SYSTEM1_DIR)

    def test_acts_on_an_answer_that_clears_the_thresholds(self) -> None:
        outcome = triage(OUTAGE, existing, self.replay)
        self.assertEqual(outcome.by, "model", outcome)
        # ADOPT: what the recorded answer for this example says.
        self.assertEqual(outcome.value, Triage(urgent=True, area="bug"))

    def test_provider_error_when_nothing_is_recorded(self) -> None:
        self.assert_fell_back(triage(NEVER_RECORDED, existing, self.replay), "provider-error")

    def test_refused_when_the_state_is_too_large(self) -> None:
        huge = Ticket(subject="Long", body="word " * 40_000)
        self.assert_fell_back(triage(huge, existing, self.replay), "refused")

    def test_engine_unavailable_without_decide(self) -> None:
        saved = policy.DECIDE
        policy.DECIDE = [os.path.join(HERE, "no-such-decide")]
        try:
            self.assert_fell_back(triage(OUTAGE, existing, self.replay), "engine-unavailable")
        finally:
            policy.DECIDE = saved
            policy._protocol_checked = None

    def test_a_transient_protocol_failure_is_tried_again(self) -> None:
        saved = policy.DECIDE
        policy.DECIDE = [sys.executable, "-c", "pass"]  # prints nothing, as a failed start would
        try:
            self.assert_fell_back(triage(OUTAGE, existing, self.replay), "engine-unavailable")
        finally:
            policy.DECIDE = saved
        self.assertEqual(triage(OUTAGE, existing, self.replay).by, "model")

    def test_a_decide_without_runtime_is_settled_once(self) -> None:
        saved = policy.DECIDE
        old = 'print(\'{"v": 1, "ok": false}\'); raise SystemExit(2)'
        policy.DECIDE = [sys.executable, "-c", old]
        try:
            outcome = triage(OUTAGE, existing, self.replay)
            self.assert_fell_back(outcome, "engine-unavailable")
            self.assertIn("upgrade", outcome.detail)
        finally:
            policy.DECIDE = saved
        # Settled for the process: the real `decide` isn't asked again.
        self.assert_fell_back(triage(OUTAGE, existing, self.replay), "engine-unavailable")

    @unittest.skipIf(LIVE_SKIP, "EGRESS is on: this test would send")
    def test_no_git_and_a_read_only_root(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = os.path.join(tmp, "system1")
            shutil.copytree(os.path.join(SYSTEM1_DIR, "fixtures"), os.path.join(root, "fixtures"))
            for here, dirs, files in os.walk(root, topdown=False):
                for name in files:
                    os.chmod(os.path.join(here, name), stat.S_IRUSR)
                os.chmod(here, stat.S_IRUSR | stat.S_IXUSR)
            cwd = os.getcwd()
            os.chdir(tmp)
            try:
                answered_ = triage(OUTAGE, existing, PolicyOptions(enabled=True, replay=True, root=root))
                self.assertEqual(answered_.by, "model", answered_)
                live = triage(OUTAGE, existing, PolicyOptions(enabled=True, root=root))
                self.assert_fell_back(live, "egress-off")
            finally:
                os.chdir(cwd)
                for here, dirs, files in os.walk(root):
                    os.chmod(here, stat.S_IRWXU)
                    for name in files:
                        os.chmod(os.path.join(here, name), stat.S_IRUSR | stat.S_IWUSR)


class Thresholds(FallsBack):
    def test_falls_back_when_undecided(self) -> None:
        def engine(_r: dict[str, Any], _o: PolicyOptions) -> dict[str, Any]:
            return {"ok": False, "reason": "undecided", "detail": "undecided: urgent", "ledger": "memory"}

        options = PolicyOptions(enabled=True, replay=True, engine=engine)
        self.assert_fell_back(triage(OUTAGE, existing, options), "undecided")

    def test_falls_back_when_urgent_is_between_the_bars(self) -> None:
        self.assert_fell_back(triage(OUTAGE, existing, answered(0.62, "bug", 0.9)), "below-threshold")

    def test_falls_back_when_the_area_is_below_its_bar(self) -> None:
        self.assert_fell_back(triage(OUTAGE, existing, answered(0.9, "bug", 0.4)), "below-threshold")

    def test_acts_at_the_bars_and_traces_each_branch(self) -> None:
        outcome = triage(OUTAGE, existing, answered(0.3, "billing", 0.6))
        self.assertEqual(outcome.by, "model")
        self.assertEqual(outcome.value, Triage(urgent=False, area="billing"))
        self.assertEqual([step.split(":")[0] for step in outcome.trace], ["model", "urgent", "area"])

    def test_answers_of_the_wrong_shape_are_below_the_bar(self) -> None:
        self.assertIsNone(policy.from_answers({}))


class Mapping(unittest.TestCase):
    def test_maps_every_output_into_the_answer_space(self) -> None:
        for key in QUESTIONS["area"]["criteria"]:
            for urgent in (True, False):
                mapped = to_answer_space(Triage(urgent=urgent, area=key))
                self.assertEqual(mapped, {"urgent": 1 if urgent else 0, "area": key})

    def test_refuses_a_value_the_question_set_does_not_offer(self) -> None:
        with self.assertRaises(ValueError):
            to_answer_space(Triage(urgent=True, area="sales"))  # type: ignore[arg-type]
        with self.assertRaises(ValueError):
            to_answer_space(Triage(urgent="yes", area="bug"))  # type: ignore[arg-type]


class Shadow(unittest.TestCase):
    def test_a_torn_last_line_does_not_swallow_the_next_row(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            file = os.path.join(tmp, "captured.jsonl")
            with open(file, "w", encoding="utf-8") as f:
                f.write('{"id": "t0", "sta')
            capture_shadow([("t1", OUTAGE)], lambda _t: CurrentRun(EXISTING), file=file, warn=lambda _m: None)
            with open(file, encoding="utf-8") as f:
                self.assertEqual(json.loads(f.read().split("\n")[1])["id"], "t1")

    def test_one_row_per_input_unknown_cost_and_a_warning(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            file = os.path.join(tmp, "captured.jsonl")
            warnings: list[str] = []
            broken = Ticket(subject="Broken", body="x")

            def current(ticket: Ticket) -> CurrentRun:
                if ticket is broken:
                    raise RuntimeError("the existing mechanism failed")
                if ticket is OUTAGE:
                    return CurrentRun(Triage(urgent=True, area="bug"), {"cost": 0.0004})
                return CurrentRun(Triage(urgent=False, area="other"))

            samples = [("t1", OUTAGE), ("t2", NEVER_RECORDED), ("t3", broken)]
            summary = capture_shadow(samples, current, file=file, warn=warnings.append)
            self.assertEqual(summary.written, 2)
            self.assertEqual([i for i, _ in summary.failed], ["t3"])
            self.assertIn("raw inputs", "\n".join(warnings))
            with open(file, encoding="utf-8") as f:
                rows = [json.loads(line) for line in f]
            self.assertEqual(rows[0]["current"], {"urgent": 1, "area": "bug"})
            self.assertEqual(rows[0]["state"], policy.to_state(OUTAGE))
            self.assertEqual(rows[0]["usage"], {"cost": 0.0004})
            self.assertNotIn("usage", rows[1])
            self.assertIsInstance(rows[1]["latencyMs"], int)

            odd = capture_shadow(
                [("u1", OUTAGE), ("u2", OUTAGE)],
                lambda _t: CurrentRun(EXISTING, {"cost": float("nan"), "input_tokens": 3}),
                file=file,
                warn=lambda _m: None,
            )
            self.assertEqual(odd.written, 2)

            bad = capture_shadow(
                [(5, OUTAGE), ("  ", OUTAGE)], current, file=file, warn=lambda _m: None  # type: ignore[list-item]
            )
            self.assertEqual([i for i, _ in bad.failed], ["5", "  "])

            again = capture_shadow(samples[:1], lambda _t: CurrentRun(EXISTING), file=file, warn=lambda _m: None)
            self.assertEqual(again.skipped, ["t1"])


if __name__ == "__main__":
    unittest.main()
