/**
 * The grant scan for this module's tests, generated by system1 `adopt`, and
 * the same scan `pnpm validate` runs over adopt's templates (0020).
 *
 * `adopt` only ever writes the marked line set to "off"; turning it on is the
 * user's edit. This is an allowlist for the name, read one line at a time:
 * - the marked line is a `const` (TS) or `Final` (Python) set to "off";
 * - every other use of the name in code is a comparison, an import, an
 *   `(name, "off")` assertion, or the runtime's option given exactly the name
 *   as the last property, closing its object, in the file that declares it;
 * - a Unicode line separator is refused, since TypeScript ends a line there.
 *
 * Comment lines and string contents are skipped. It reads text, not what
 * runs: a computed key or code it doesn't parse can still pass it, so the
 * user's review of the diff is the control. The words are assembled so this
 * file carries no grant of its own.
 */
const [E, e] = ["EG" + "RESS", "egr" + "ess"]
const MARKER = ["system1", ": runtime ", e].join("")

/** Everything in `source` that could grant runtime egress; `python` for a `.py` file. */
export function grantProblems(source: string, python = false): string[] {
  const problems: string[] = []
  if (/[\u2028\u2029]/.test(source)) problems.push("a Unicode line separator (U+2028/U+2029)")
  const lines = source.split(/\r\n|[\r\n\u2028\u2029]/)
  const marked = lines.filter((line) => line.includes(MARKER))
  if (marked.length > 1) problems.push(`${marked.length} lines carry the marker, not one`)
  const offLine = new RegExp(
    `^(?:(?:export\\s+)?const\\s+${E}\\s*(?::\\s*[\\w.[\\]|,"' ]+?\\s*)?=\\s*(["'])off\\1\\s*(?:(?:as|satisfies)\\s+[\\w.]+\\s*)?;?\\s*\\/\\/|${E}\\s*:\\s*Final\\s*=\\s*(["'])off\\2\\s*#)\\s*${MARKER}`,
  )
  const declares = marked.length === 1 && offLine.test(marked[0] as string)
  const comment = python ? /^\s*#/ : /^\s*(?:\/\/|\/\*|\*)/
  const name = new RegExp(`\\b${E}\\b`, "g")
  const word = new RegExp(`\\b${e}\\b(?!-)`, "g")
  const oneLineImport =
    /^\s*(?:import\s*(?:type\s*)?\{[^}]*\}\s*from\s|from\s+[\w.]+\s+import\s+[\w\s,]*$)/
  const givenBefore = new RegExp(`\\b${e}\\s*:\\s*$`)
  const closes = new RegExp(`^\\s*:\\s*${E}\\s*[})]`)
  const lastLine = new RegExp(`^\\s*:\\s*${E}\\s*,?\\s*$`)
  const byName = new RegExp(`["']${e}["']|\\.${e}\\b`)
  const consent = new RegExp(`${e}Consent`, "i")
  const env = /process\.env|os\.environ|getenv/
  const reflection =
    /\bsetattr\s*\(|\bglobals\s*\(|\b__dict__\b|Object\.defineProperty|Reflect\.set/
  for (const [i, line] of lines.entries()) {
    const at = `line ${i + 1}`
    if (line.includes(MARKER)) {
      if (!offLine.test(line)) problems.push(`${at}: the marked line isn't a constant set to "off"`)
      continue
    }
    if (comment.test(line)) continue
    const code = line
      .replace(/(?<![fF])"(?:[^"\\]|\\.)*"|(?<![fF])'(?:[^'\\]|\\.)*'/g, '""')
      .replaceAll(`\`${E}\``, "")
    for (const m of code.matchAll(name)) {
      const before = code.slice(0, m.index)
      const after = code.slice((m.index ?? 0) + m[0].length)
      const allowed =
        /^\s*[!=]==?(?!=)/.test(after) ||
        /[!=]==?\s*$/.test(before) ||
        oneLineImport.test(code) ||
        (/\(\s*$/.test(before) && /^\s*,\s*""\s*\)/.test(after)) ||
        inImportList(lines, i) ||
        givenBefore.test(before)
      if (!allowed) problems.push(`${at}: ${E} used other than as allowed`)
    }
    for (const m of code.matchAll(word)) {
      const rest = code.slice((m.index ?? 0) + m[0].length)
      if (/^\s*[:=](?!=)/.test(rest)) {
        const last =
          lastLine.test(rest) &&
          /^\s*\}/.test(lines.slice(i + 1).find((l) => l.trim() !== "") ?? "")
        if (!closes.test(rest) && !last)
          problems.push(`${at}: the runtime given anything but ${E}, last, closing its object`)
        else if (!declares)
          problems.push(`${at}: the runtime given a ${E} this file doesn't declare`)
      } else if (/^\s*[,})]/.test(rest)) problems.push(`${at}: the grant passed as a variable`)
    }
    if (byName.test(line)) problems.push(`${at}: the grant set by name`)
    if (consent.test(line)) problems.push(`${at}: a consent option`)
    if (reflection.test(code)) problems.push(`${at}: a binding set by reflection`)
    if (new RegExp(`\\b${E}\\b`).test(line) && env.test(line))
      problems.push(`${at}: ${E} read from the environment`)
  }
  return problems
}

/** Is line `i` a bare item of a multi-line import (TS `import {…} from`, Python `from … import (…)`)? */
function inImportList(lines: string[], i: number): boolean {
  if (!new RegExp(`^\\s*${E}\\s*,?\\s*$`).test(lines[i] as string)) return false
  const item = /^\s*(?:type\s+)?\w+(?:\s+as\s+\w+)?\s*,?\s*$/
  let start = i - 1
  while (start >= 0 && item.test(lines[start] as string)) start--
  let end = i + 1
  while (end < lines.length && item.test(lines[end] as string)) end++
  const open = lines[start] ?? ""
  const close = lines[end] ?? ""
  return (
    (/^\s*import\s*(?:type\s*)?\{\s*$/.test(open) && /^\s*\}\s*from\s/.test(close)) ||
    (/^\s*from\s+[\w.]+\s+import\s*\(\s*$/.test(open) && /^\s*\)\s*$/.test(close))
  )
}
