/**
 * The existing mechanism's output in the spec's answer space, generated by
 * system1 `adopt` for `ticket-triage`. The shadow harness writes it as each
 * captured row's `current`, so `decide compare` can set the existing answers
 * beside the decision model's, question by question.
 *
 * Strict, like `compare`'s own reading: a value the question set doesn't offer
 * throws rather than being guessed into one.
 * ADOPT: one entry per question in the spec, from the app's own output type.
 */
import { QUESTIONS, type Triage } from "./policy.ts"

/** One value per question: a choice's key, a score's level, or a noul's 0–1. */
export type CurrentAnswers = Record<string, string | number>

export function toAnswerSpace(output: Triage): CurrentAnswers {
  if (typeof output?.urgent !== "boolean") throw new Error("urgent is not a boolean")
  const area = QUESTIONS.area
  if (area?.type !== "choice" || !Object.hasOwn(area.criteria, output.area))
    throw new Error(`area "${String(output?.area)}" is not an offered option`)
  return {
    // A yes/no mechanism is certain either way, so its noul is 1 or 0.
    urgent: output.urgent ? 1 : 0,
    area: output.area,
  }
}
