/**
 * Offline tests for the `ticket-triage` policy module, generated by system1
 * `adopt`. They answer from the spec's recorded fixtures (replay): nothing is
 * sent, and no key or grant is needed.
 *
 * ADOPT: the test runner and paths of the repo. Record fresh fixtures with
 * `decide spec check ticket-triage --live` after changing the questions or the
 * states below; the states here are the spec's examples, so their recorded
 * answers are what replay serves.
 */
import assert from "node:assert/strict"
import {
  chmodSync,
  cpSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { after, describe, it } from "node:test"
import { fileURLToPath } from "node:url"
import { grantProblems } from "./grants.ts"
import { toAnswerSpace } from "./mapping.ts"
import {
  EGRESS,
  fromAnswers,
  type Outcome,
  QUESTIONS,
  type Ticket,
  type Triage,
  triage,
} from "./policy.ts"
import { captureShadow } from "./shadow.ts"

/** ADOPT: the repo's `.system1` directory, which holds `fixtures/ticket-triage/`. */
const SYSTEM1_DIR = fileURLToPath(new URL("../.system1", import.meta.url))
/** ADOPT: the module files `adopt` wrote, checked for a grant below. */
const MODULE_FILES = ["policy.ts", "mapping.ts", "shadow.ts", "grants.ts"].map((name) =>
  fileURLToPath(new URL(`./${name}`, import.meta.url)),
)

// ADOPT: the spec's examples, as tickets. The first has a recorded answer.
const OUTAGE: Ticket = {
  subject: "Dashboard down for our whole team",
  body: "Since 9am every page returns a 500 error and nobody here can work.",
}
/** The comment on the one grant line, assembled so this file carries none. */
const MARKER = ["system1", ": runtime ", "egr", "ess"].join("")

const NEVER_RECORDED: Ticket = { subject: "Never recorded", body: "No fixture holds this ticket." }

const EXISTING: Triage = { urgent: false, area: "other" }
const existing = () => EXISTING

/** Tests that run in live mode are skipped once EGRESS is on, so a test never sends. */
const LIVE_SKIP = EGRESS === "off" ? false : "EGRESS is on: this test would send"

const scratch: string[] = []
function tempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "system1-policy-"))
  scratch.push(dir)
  return dir
}
after(() => {
  for (const dir of scratch) {
    makeWritable(dir)
    rmSync(dir, { recursive: true, force: true })
  }
})

/** A copy of the recorded fixtures in a directory with no `.git`, made read-only. */
function readOnlyRoot(): string {
  const root = join(tempDir(), "system1")
  cpSync(join(SYSTEM1_DIR, "fixtures"), join(root, "fixtures"), { recursive: true })
  for (const path of walk(root).reverse())
    chmodSync(path, statSync(path).isDirectory() ? 0o555 : 0o444)
  return root
}

function walk(dir: string): string[] {
  return [
    dir,
    ...readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
      e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)],
    ),
  ]
}

function makeWritable(dir: string) {
  for (const path of walk(dir)) chmodSync(path, statSync(path).isDirectory() ? 0o755 : 0o644)
}

const fellBack = (outcome: Outcome, reason: string) => {
  assert.equal(outcome.by, "existing")
  assert.deepEqual(outcome.value, EXISTING)
  if (outcome.by === "existing") assert.equal(outcome.reason, reason)
}

describe("runtime egress", () => {
  // When you switch EGRESS on, change this expectation in the same reviewed edit.
  it("is off as generated", () => {
    assert.equal(EGRESS, "off")
  })

  it("has no grant in the module's source, in any spelling", () => {
    const policy = readFileSync(MODULE_FILES[0] as string, "utf8")
    assert.equal(policy.split("\n").filter((line) => line.includes(MARKER)).length, 1)
    for (const file of MODULE_FILES)
      assert.deepEqual(grantProblems(readFileSync(file, "utf8")), [], file)
  })

  it("catches the grants it scans for", () => {
    // Assembled, so this file holds none of them.
    const [E, e] = ["EG" + "RESS", "egr" + "ess"]
    for (const bad of [
      `export const ${E}: "on" | "off" = "o${"n"}" // system1${": runtime "}${e}`,
      `${E} = 'o${"n"}'`,
      `${E}=process.env.X`,
      `${E} = "off"`,
      `${E} = "off" && "on" // system1${": runtime "}${e}`,
      `const SEND = process.env.X === "1"\nf({ ${e}: ${E} === "off" && SEND ? "on" : ${E} })`,
      `import { ${E} } from "./settings.ts" // system1${": runtime "}${e}`,
      `import { ${E} } from "./settings.ts"\nf({ ${e}: ${E} })`,
      `const { ${E} } = settings`,
      `o["${e}"] = "on"`,
      `options.${e} = "on"`,
      `function r(${e}) { f({ ${e}, x }) }`,
      `${E}: Final = os.environ.get("X", "off")`,
      `${e}: true,`,
      `${e}: grant,`,
      `${e}Consent: true`,
      `const g = os.environ["${E}"]`,
      `// system1${": runtime "}${e}\n// system1${": runtime "}${e}`,
    ])
      assert.notDeepEqual(grantProblems(bad), [], bad)
  })
})

describe("inert by default", () => {
  it("takes the existing path when not enabled", async () => {
    let calls = 0
    const outcome = await triage(OUTAGE, () => {
      calls++
      return EXISTING
    })
    fellBack(outcome, "disabled")
    assert.equal(calls, 1)
  })

  it("takes the existing path when enabled but EGRESS is off", { skip: LIVE_SKIP }, async () => {
    fellBack(await triage(OUTAGE, existing, { enabled: true }), "egress-off")
  })
})

describe("answers from recorded fixtures (replay)", () => {
  const replay = { enabled: true, mode: "replay" as const, root: SYSTEM1_DIR }

  it("acts on an answer that clears the thresholds", async () => {
    const outcome = await triage(OUTAGE, existing, replay)
    assert.equal(outcome.by, "model", JSON.stringify(outcome))
    // ADOPT: what the recorded answer for this example says.
    assert.deepEqual(outcome.value, { urgent: true, area: "bug" })
  })

  it("falls back on a provider error: no recorded answer", async () => {
    fellBack(await triage(NEVER_RECORDED, existing, replay), "provider-error")
  })

  it("falls back when the state is refused as too large", async () => {
    const huge = { subject: "Long", body: "word ".repeat(40_000) }
    fellBack(await triage(huge, existing, replay), "refused")
  })

  it("works from a directory with no .git and a read-only root", { skip: LIVE_SKIP }, async () => {
    const cwd = process.cwd()
    process.chdir(tempDir())
    try {
      const root = readOnlyRoot()
      const answered = await triage(OUTAGE, existing, { ...replay, root })
      assert.equal(answered.by, "model")
      fellBack(await triage(OUTAGE, existing, { enabled: true, root }), "egress-off")
    } finally {
      process.chdir(cwd)
    }
  })
})

describe("thresholds", () => {
  const answered = (urgent: number, area: string, p: number) => ({
    enabled: true,
    mode: "replay" as const,
    runtime: {
      decide: async () => ({
        ok: true as const,
        source: "replay" as const,
        answers: {
          urgent: { type: "noul" as const, noul: urgent },
          area: {
            type: "choice" as const,
            choice: area,
            probabilities: { [area]: p },
            confidence: p,
          },
        },
        usage: { input_tokens: 0, output_tokens: 0, cost: 0 },
        latencyMs: 1,
        ledger: "memory" as const,
      }),
    },
  })

  it("falls back when the model is undecided", async () => {
    const undecided = {
      enabled: true,
      mode: "replay" as const,
      runtime: {
        decide: async () => ({
          ok: false as const,
          reason: "undecided" as const,
          detail: "undecided: urgent",
          ledger: "memory" as const,
        }),
      },
    }
    fellBack(await triage(OUTAGE, existing, undecided), "undecided")
  })

  it("falls back when urgent sits between the bars", async () => {
    fellBack(await triage(OUTAGE, existing, answered(0.62, "bug", 0.9)), "below-threshold")
  })

  it("falls back when the chosen area is below its bar", async () => {
    fellBack(await triage(OUTAGE, existing, answered(0.9, "bug", 0.4)), "below-threshold")
  })

  it("acts at the bars, and traces each branch", async () => {
    const outcome = await triage(OUTAGE, existing, answered(0.3, "billing", 0.6))
    assert.equal(outcome.by, "model")
    assert.deepEqual(outcome.value, { urgent: false, area: "billing" })
    assert.deepEqual(
      outcome.trace.map((t) => t.step),
      ["model", "urgent", "area"],
    )
  })

  it("reads answers of the wrong shape as below the bar", () => {
    assert.equal(fromAnswers({}), undefined)
  })
})

describe("output → answer mapping", () => {
  it("maps every output into the answer space", () => {
    const area = QUESTIONS.area
    assert.equal(area?.type, "choice")
    for (const key of Object.keys(area?.type === "choice" ? area.criteria : {}))
      for (const urgent of [true, false]) {
        const mapped = toAnswerSpace({ urgent, area: key as Triage["area"] })
        assert.deepEqual(mapped, { urgent: urgent ? 1 : 0, area: key })
      }
  })

  it("refuses a value the question set doesn't offer", () => {
    assert.throws(() => toAnswerSpace({ urgent: true, area: "sales" as Triage["area"] }))
    assert.throws(() => toAnswerSpace({ urgent: "yes" as unknown as boolean, area: "bug" }))
  })
})

describe("shadow capture", () => {
  it("doesn't let a torn last line swallow the next row", async () => {
    const file = join(tempDir(), "captured.jsonl")
    writeFileSync(file, '{"id": "t0", "sta')
    await captureShadow([{ id: "t1", ticket: OUTAGE }], async () => ({ output: EXISTING }), {
      file,
      warn: () => {},
    })
    assert.equal(JSON.parse(readFileSync(file, "utf8").split("\n")[1] as string).id, "t1")
  })

  it("writes one row per input, leaves cost unknown when it is, and warns", async () => {
    const file = join(tempDir(), "captured.jsonl")
    const warnings: string[] = []
    const samples = [
      { id: "t1", ticket: OUTAGE },
      { id: "t2", ticket: NEVER_RECORDED },
      { id: "t3", ticket: { subject: "Broken", body: "x" } },
    ]
    const summary = await captureShadow(
      samples,
      async (ticket) => {
        if (ticket.body === "x") throw new Error("the existing mechanism failed")
        return ticket === OUTAGE
          ? { output: { urgent: true, area: "bug" }, usage: { cost: 0.0004 } }
          : { output: { urgent: false, area: "other" } }
      },
      { file, warn: (m) => warnings.push(m) },
    )
    assert.equal(summary.written, 2)
    assert.deepEqual(
      summary.failed.map((f) => f.id),
      ["t3"],
    )
    assert.match(warnings.join("\n"), /raw inputs/)
    const rows = readFileSync(file, "utf8")
      .trim()
      .split("\n")
      .map((l) => JSON.parse(l))
    assert.deepEqual(rows[0].current, { urgent: 1, area: "bug" })
    assert.equal(
      rows[0].state,
      "Subject: Dashboard down for our whole team\n\nSince 9am every page returns a 500 error and nobody here can work.",
    )
    assert.deepEqual(rows[0].usage, { cost: 0.0004 })
    assert.equal(rows[1].usage, undefined)
    assert.equal(typeof rows[1].latencyMs, "number")

    const odd = await captureShadow(
      [{ id: "u1", ticket: OUTAGE }],
      async () => ({
        output: EXISTING,
        usage: { cost: 0.001, input_tokens: 5n as unknown as number },
      }),
      { file, warn: () => {} },
    )
    assert.equal(odd.written, 1)
    const last = readFileSync(file, "utf8").trim().split("\n").at(-1) as string
    assert.deepEqual(JSON.parse(last).usage, { cost: 0.001 })

    const bad = await captureShadow(
      [
        { id: 5 as unknown as string, ticket: OUTAGE },
        { id: "  ", ticket: OUTAGE },
      ],
      async () => ({ output: EXISTING }),
      { file, warn: () => {} },
    )
    assert.deepEqual(
      bad.failed.map((f) => f.id),
      ["5", "  "],
    )

    const again = await captureShadow(samples.slice(0, 1), async () => ({ output: EXISTING }), {
      file,
      warn: () => {},
    })
    assert.deepEqual(again.skipped, ["t1"])
  })
})
