/**
 * Decision-model policy for `ticket-triage`, generated by system1 `adopt` from
 * `.system1/specs/ticket-triage.yaml`, against the `@garygentry/system1-core`
 * version pinned exactly in package.json.
 *
 * It sits in front of the existing mechanism and is inert until you switch it on
 * twice: `enabled: true` where you call it, and the `EGRESS` line below. Until
 * both are on, every call takes the existing path. Any call the model can't
 * answer well enough also takes the existing path, with a reason code to log.
 *
 * ADOPT: every `ADOPT:` comment marks what to change for the repo's own spec,
 * types and idiom. Keep the `EGRESS` line exactly as it is, set to "off".
 */
import {
  type Answers,
  createPolicyRuntime,
  type PolicyRuntime,
  type QuestionSet,
  type ReasonCode,
} from "@garygentry/system1-core/runtime"

// Runtime egress for this module. `adopt` writes "off" and never anything else.
// Changing it to "on" is your decision, made in reviewed code: it lets this
// module send ticket text to OpenRouter's decision model. Nothing else turns it on.
export const EGRESS: "on" | "off" = "off" // system1: runtime egress (only you switch this on)

/** Measured spend a UTC day before every call takes the existing path (`budget`). */
export const MAX_USD_PER_DAY = 1.0
/** The decision model this module was generated and recorded against. */
export const MODEL = "typesafe/jev-1.13"
/** The spec's name: the fixture namespace its recorded answers live under. */
export const SPEC = "ticket-triage"

// ADOPT: the spec's questions, copied verbatim. Recorded answers are keyed on
// them, so an edit here needs fresh fixtures (`decide spec check <spec> --live`).
export const QUESTIONS: QuestionSet = {
  urgent: {
    type: "noul",
    instructions:
      "The ticket reports something that needs a reply within the hour: an outage, lost data, a security problem, or a customer blocked from working.",
    criteria: {
      true: "Something is down, lost, exposed or blocking the customer's work now.",
      false: "A question, a request, or a problem with a workaround.",
    },
  },
  area: {
    type: "choice",
    instructions: "Which team should handle this ticket?",
    criteria: {
      billing: "Charges, invoices, refunds, plans or payment methods.",
      bug: "The product behaves wrongly or fails.",
      account: "Sign-in, passwords, users, permissions or settings.",
      other: "None of the above.",
    },
  },
}

// ADOPT: the spec's `policy.thresholds`. An answer between the two noul bars,
// or a choice below its bar, is not acted on: the call takes the existing path.
export const THRESHOLDS = {
  /** `urgent` at or above this is urgent. */
  urgentAtLeast: 0.7,
  /** `urgent` at or below this is not urgent. */
  notUrgentAtMost: 0.3,
  /** The chosen `area` needs at least this probability. */
  areaAtLeast: 0.6,
} as const

// ADOPT: the existing mechanism's input and output types, as the app has them.
export interface Ticket {
  subject: string
  body: string
}
export type Area = "billing" | "bug" | "account" | "other"
export interface Triage {
  urgent: boolean
  area: Area
}

/**
 * What the model sees for one ticket. The shadow harness captures the same
 * state, so `decide compare` judges exactly what this module would send.
 * ADOPT: build it from the inputs the existing mechanism reads, and nothing more.
 */
export function toState(ticket: Ticket): string {
  return `Subject: ${ticket.subject}\n\n${ticket.body}`
}

/** One step of the decision, for a log line or a test. */
export interface TraceStep {
  step: string
  detail?: string
}

export type Outcome =
  | { value: Triage; by: "model"; trace: TraceStep[] }
  | {
      value: Triage
      by: "existing"
      /** Why the model's answer wasn't used. */
      reason: ReasonCode | "disabled" | "below-threshold"
      detail: string
      trace: TraceStep[]
    }

export interface PolicyOptions {
  /** The app-level switch. False (the default) keeps the existing path for every call. */
  enabled?: boolean
  /** Where the spend ledger and recorded answers live. Without it, spend is counted in memory. */
  root?: string
  /** `replay` answers from `root`'s recorded fixtures and sends nothing: how the tests run. */
  mode?: "live" | "replay"
  timeoutMs?: number
  /** For tests: a stand-in for the runtime. */
  runtime?: Pick<PolicyRuntime, "decide">
}

/**
 * Triage a ticket with the decision model, falling back to `existing` when the
 * policy is off or the model's answer doesn't clear the spec's thresholds.
 * It never throws because of the model; `existing` may.
 */
export async function triage(
  ticket: Ticket,
  existing: (ticket: Ticket) => Triage | Promise<Triage>,
  options: PolicyOptions = {},
): Promise<Outcome> {
  const trace: TraceStep[] = []
  const fallBack = async (
    reason: ReasonCode | "disabled" | "below-threshold",
    detail: string,
  ): Promise<Outcome> => {
    trace.push({ step: "existing", detail: reason })
    return { value: await existing(ticket), by: "existing", reason, detail, trace }
  }
  if (options.enabled !== true) return fallBack("disabled", "the policy is not enabled")
  const mode = options.mode ?? "live"
  // The runtime refuses too; checking here keeps an off module from loading anything.
  if (mode === "live" && EGRESS !== "on")
    return fallBack("egress-off", "runtime egress is off (this module's EGRESS line)")

  const runtime = options.runtime ?? runtimeFor(options)
  const result = await runtime.decide({
    questions: QUESTIONS,
    state: toState(ticket),
    namespace: SPEC,
  })
  // `=== false`, not `!`: it narrows the union without strictNullChecks too.
  if (result.ok === false) {
    trace.push({ step: "model", detail: result.reason })
    return fallBack(result.reason, result.detail)
  }
  trace.push({ step: "model", detail: result.source })
  const value = fromAnswers(result.answers, trace)
  return value ? { value, by: "model", trace } : fallBack("below-threshold", traceLine(trace))
}

/**
 * The model's answers as the app's output, or `undefined` when one doesn't
 * clear its threshold. Each check is added to `trace`.
 * ADOPT: one branch per question, reading the spec's thresholds.
 */
export function fromAnswers(answers: Answers, trace: TraceStep[] = []): Triage | undefined {
  const urgent = answers.urgent
  const area = answers.area
  if (urgent?.type !== "noul" || area?.type !== "choice") {
    trace.push({ step: "answers", detail: "missing or of the wrong type" })
    return undefined
  }
  let isUrgent: boolean | undefined
  if (urgent.noul >= THRESHOLDS.urgentAtLeast) isUrgent = true
  else if (urgent.noul <= THRESHOLDS.notUrgentAtMost) isUrgent = false
  trace.push({
    step: "urgent",
    detail: `${urgent.noul.toFixed(2)} → ${isUrgent === undefined ? "between the bars" : isUrgent}`,
  })
  const p = area.probabilities[area.choice] ?? 0
  const chosen = p >= THRESHOLDS.areaAtLeast && isArea(area.choice) ? area.choice : undefined
  trace.push({
    step: "area",
    detail: `${area.choice} ${p.toFixed(2)} → ${chosen ?? "below the bar"}`,
  })
  return isUrgent === undefined || chosen === undefined
    ? undefined
    : { urgent: isUrgent, area: chosen }
}

function isArea(key: string): key is Area {
  return key === "billing" || key === "bug" || key === "account" || key === "other"
}

const traceLine = (trace: TraceStep[]) =>
  trace.map((t) => (t.detail ? `${t.step}: ${t.detail}` : t.step)).join("; ")

// One runtime per root and mode, so the daily cap counts every call in the process.
const runtimes = new Map<string, PolicyRuntime>()
function runtimeFor(options: PolicyOptions): PolicyRuntime {
  const mode = options.mode ?? "live"
  const key = JSON.stringify([options.root ?? null, mode, options.timeoutMs ?? null])
  let runtime = runtimes.get(key)
  if (!runtime) {
    runtime = createPolicyRuntime({
      maxUsdPerDay: MAX_USD_PER_DAY,
      model: MODEL,
      mode,
      ...(options.root ? { root: options.root } : {}),
      ...(options.timeoutMs ? { timeoutMs: options.timeoutMs } : {}),
      // The runtime reads this file's EGRESS line too: both must say on. A
      // bundle without this source on disk needs "bundled", your edit.
      module: import.meta.url,
      // Last, so nothing spread above can override it.
      egress: EGRESS,
    })
    runtimes.set(key, runtime)
  }
  return runtime
}
