/**
 * Shadow capture for `ticket-triage`, generated by system1 `adopt`. It runs the
 * existing mechanism over sampled inputs and appends one row per input to
 * `.system1/compare/ticket-triage/captured.jsonl`:
 *
 *   {id, state, current, usage?, latencyMs}
 *
 * `decide compare ticket-triage` then sends each `state` to the decision model
 * and sets its answers beside `current`. The engine never runs this code.
 *
 * - **The file holds raw inputs** (each ticket's text). Keep it out of git:
 *   `.system1/compare/*\/captured.jsonl` belongs in `.gitignore`.
 * - **The existing mechanism runs for real here.** If it is a model call, every
 *   row costs what it costs and sends what it sends, outside system1's checks.
 * - A row without `usage` means its cost is unknown, never zero.
 *
 * ADOPT: the sample source and the call to the existing mechanism.
 */
import { appendFileSync, existsSync, mkdirSync, readFileSync } from "node:fs"
import { dirname } from "node:path"
import { toAnswerSpace } from "./mapping.ts"
import { SPEC, type Ticket, type Triage, toState } from "./policy.ts"

export const CAPTURE_FILE = `.system1/compare/${SPEC}/captured.jsonl`

/** What one run of the existing mechanism returned, and what it cost if known. */
export interface CurrentRun {
  output: Triage
  /** USD, with token counts when known. Leave it out when the cost isn't known. */
  usage?: { cost: number; input_tokens?: number; output_tokens?: number }
}

export interface ShadowSummary {
  file: string
  written: number
  /** Ids already in the file, left as they are. */
  skipped: string[]
  /** Inputs the existing mechanism, or the mapping, failed on: no row is written. */
  failed: Array<{ id: string; error: string }>
}

export async function captureShadow(
  samples: Iterable<{ id: string; ticket: Ticket }> | AsyncIterable<{ id: string; ticket: Ticket }>,
  current: (ticket: Ticket) => Promise<CurrentRun>,
  options: { file?: string; warn?: (message: string) => void } = {},
): Promise<ShadowSummary> {
  const file = options.file ?? CAPTURE_FILE
  const warn = options.warn ?? ((message: string) => console.warn(message))
  warn(
    `system1 shadow: ${file} holds raw inputs. Keep it out of git, and delete it when the comparison is done.`,
  )
  mkdirSync(dirname(file), { recursive: true })
  const seen = existingIds(file)
  // A torn last line (a crash mid-write) would swallow the next row.
  if (existsSync(file) && !/(^|\n)$/.test(readFileSync(file, "utf8"))) appendFileSync(file, "\n")
  const summary: ShadowSummary = { file, written: 0, skipped: [], failed: [] }
  for await (const { id, ticket } of samples) {
    if (typeof id !== "string" || id.trim() === "") {
      summary.failed.push({ id: String(id), error: "an id must be a non-empty string" })
      continue
    }
    if (seen.has(id)) {
      summary.skipped.push(id)
      continue
    }
    const started = performance.now()
    let line: string
    try {
      const run = await current(ticket)
      const latencyMs = Math.round(performance.now() - started)
      const row: Record<string, unknown> = {
        id,
        state: toState(ticket),
        current: toAnswerSpace(run.output),
        latencyMs,
      }
      const usage = usageOf(run.usage)
      if (usage) row.usage = usage
      line = JSON.stringify(row)
    } catch (error) {
      summary.failed.push({ id, error: error instanceof Error ? error.message : String(error) })
      continue
    }
    appendFileSync(file, `${line}\n`)
    seen.add(id)
    summary.written++
  }
  return summary
}

/**
 * The cost as `compare` reads it: a finite cost of at least 0, with token
 * counts when they are numbers. Anything else means unknown.
 */
function usageOf(raw: CurrentRun["usage"]): CurrentRun["usage"] | undefined {
  const number = (v: unknown) =>
    typeof v === "number" && Number.isFinite(v) && v >= 0 ? v : undefined
  const cost = number(raw?.cost)
  if (cost === undefined) return undefined
  const input = number(raw?.input_tokens)
  const output = number(raw?.output_tokens)
  return {
    cost,
    ...(input !== undefined ? { input_tokens: input } : {}),
    ...(output !== undefined ? { output_tokens: output } : {}),
  }
}

/** Ids already captured: `compare` reads a repeated id as a bad line. */
function existingIds(file: string): Set<string> {
  const ids = new Set<string>()
  if (!existsSync(file)) return ids
  for (const line of readFileSync(file, "utf8").split("\n")) {
    try {
      const id = (JSON.parse(line) as { id?: unknown }).id
      if (typeof id === "string") ids.add(id)
    } catch {
      // A torn line: compare reports it.
    }
  }
  return ids
}
