// Collects the licence notices of every dependency the CLI bundle inlines.
//
// The bundle is one file: npm doesn't install those packages beside it, so
// their notices have to travel with us. MIT and ISC both require the notice to
// be kept in "all copies or substantial portions" — a bundle is exactly that.
//
//   node tools/notices.mjs           write packages/cli/THIRD-PARTY-NOTICES.md
//   node tools/notices.mjs --check   fail if it is out of date

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const OUT = join(ROOT, "packages/cli/THIRD-PARTY-NOTICES.md")
const require = createRequire(join(ROOT, "packages/core/package.json"))

/** Runtime dependencies of core (what the bundle inlines) plus core itself. */
function bundled() {
  const core = JSON.parse(readFileSync(join(ROOT, "packages/core/package.json"), "utf8"))
  return Object.keys(core.dependencies ?? {}).sort()
}

/** Some packages don't export package.json, so look it up on disk. */
function packageDir(name) {
  const local = join(ROOT, "packages/core/node_modules", name)
  if (existsSync(join(local, "package.json"))) return local
  try {
    return dirname(require.resolve(`${name}/package.json`))
  } catch {
    // A package with no package.json export: walk up from its entry point.
    let dir = dirname(require.resolve(name))
    while (!existsSync(join(dir, "package.json")) && dir !== dirname(dir)) dir = dirname(dir)
    return dir
  }
}

function noticeFor(name) {
  const dir = packageDir(name)
  const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"))
  const file = readdirSync(dir).find((f) => /^(LICEN[CS]E|COPYING)/i.test(f))
  const text = file ? readFileSync(join(dir, file), "utf8").trim() : undefined
  if (!text) throw new Error(`No licence file found for ${name} in ${dir}`)
  return { name, version: pkg.version, license: pkg.license ?? "see below", text }
}

const notices = bundled().map(noticeFor)
const body = `# Third-party notices

The \`decide\` CLI ships as a single bundle with these packages compiled into
it. Their licences and copyright notices are reproduced in full, as those
licences require. Generated by \`node tools/notices.mjs\`; do not edit.

${notices.map((n) => `- ${n.name} ${n.version} (${n.license})`).join("\n")}

${notices.map((n) => `---\n\n## ${n.name} ${n.version}\n\n\`\`\`\n${n.text}\n\`\`\`\n`).join("\n")}`

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : ""
  if (current !== body) {
    console.error("THIRD-PARTY-NOTICES.md is out of date; run `node tools/notices.mjs`")
    process.exit(1)
  }
  console.log(`notices: up to date (${notices.length} packages)`)
} else {
  writeFileSync(OUT, body)
  console.log(`notices: wrote ${notices.length} packages to ${OUT}`)
}
